// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class GestionColegial_V20_R2Context : DbContext
    {
        public GestionColegial_V20_R2Context()
        {
        }

        public GestionColegial_V20_R2Context(DbContextOptions<GestionColegial_V20_R2Context> options)
            : base(options)
        {
        }

        public virtual DbSet<tbAlumnos> tbAlumnos { get; set; }
        public virtual DbSet<tbAlumnosHistorial> tbAlumnosHistorial { get; set; }
        public virtual DbSet<tbAulas> tbAulas { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbConceptosPago> tbConceptosPago { get; set; }
        public virtual DbSet<tbCuentasCobrar> tbCuentasCobrar { get; set; }
        public virtual DbSet<tbCuentasCobrarHistorial> tbCuentasCobrarHistorial { get; set; }
        public virtual DbSet<tbCursos> tbCursos { get; set; }
        public virtual DbSet<tbCursosHistorial> tbCursosHistorial { get; set; }
        public virtual DbSet<tbCursosNiveles> tbCursosNiveles { get; set; }
        public virtual DbSet<tbCursos_tbSecciones> tbCursos_tbSecciones { get; set; }
        public virtual DbSet<tbDepartamentoEmpleados> tbDepartamentoEmpleados { get; set; }
        public virtual DbSet<tbDescuentos> tbDescuentos { get; set; }
        public virtual DbSet<tbDescuentosAplicados> tbDescuentosAplicados { get; set; }
        public virtual DbSet<tbDias> tbDias { get; set; }
        public virtual DbSet<tbDuraciones> tbDuraciones { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEncargados> tbEncargados { get; set; }
        public virtual DbSet<tbEncargadosHistorial> tbEncargadosHistorial { get; set; }
        public virtual DbSet<tbEncargados_tbAlumnos> tbEncargados_tbAlumnos { get; set; }
        public virtual DbSet<tbEstados> tbEstados { get; set; }
        public virtual DbSet<tbEstadosPago> tbEstadosPago { get; set; }
        public virtual DbSet<tbFormasPago> tbFormasPago { get; set; }
        public virtual DbSet<tbHorario> tbHorario { get; set; }
        public virtual DbSet<tbHorarioAlumnos> tbHorarioAlumnos { get; set; }
        public virtual DbSet<tbHorarioAlumnosHistorial> tbHorarioAlumnosHistorial { get; set; }
        public virtual DbSet<tbHorarioProfesores> tbHorarioProfesores { get; set; }
        public virtual DbSet<tbHoras> tbHoras { get; set; }
        public virtual DbSet<tbMaterias> tbMaterias { get; set; }
        public virtual DbSet<tbMateriasHistorial> tbMateriasHistorial { get; set; }
        public virtual DbSet<tbMatriculas> tbMatriculas { get; set; }
        public virtual DbSet<tbModalidades> tbModalidades { get; set; }
        public virtual DbSet<tbMoratorias> tbMoratorias { get; set; }
        public virtual DbSet<tbNivelesEducativos> tbNivelesEducativos { get; set; }
        public virtual DbSet<tbNotas> tbNotas { get; set; }
        public virtual DbSet<tbNotasHistorial> tbNotasHistorial { get; set; }
        public virtual DbSet<tbPagos> tbPagos { get; set; }
        public virtual DbSet<tbPagosDetalle> tbPagosDetalle { get; set; }
        public virtual DbSet<tbPagosHistorial> tbPagosHistorial { get; set; }
        public virtual DbSet<tbParciales> tbParciales { get; set; }
        public virtual DbSet<tbParentescos> tbParentescos { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbPersonasHistorial> tbPersonasHistorial { get; set; }
        public virtual DbSet<tbRecibos> tbRecibos { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbSecciones> tbSecciones { get; set; }
        public virtual DbSet<tbSemestres> tbSemestres { get; set; }
        public virtual DbSet<tbTarifas> tbTarifas { get; set; }
        public virtual DbSet<tbTitulos> tbTitulos { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-06VA2CI;Initial Catalog=DB_GestionColegial;Integrated Security=True;Encrypt=False");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tbAlumnos>(entity =>
            {
                entity.HasKey(e => e.Alu_Id)
                    .HasName("PK__tbAlumno__1B389478D42CADFB");

                entity.ToTable("tbAlumnos", "app");

                entity.HasComment("Contiene la información de los alumnos.");

                entity.Property(e => e.Alu_Id).HasComment("Identificador unico del tbAlumnos.");

                entity.Property(e => e.AnioCursado).HasComment("Año en que se cursó el ciclo.\r\n");

                entity.Property(e => e.Cun_Id).HasComment("Indica el identificador único de tbCursoNiveles.");

                entity.Property(e => e.Cur_Id).HasComment("Indica el identificador único de tbCursos.");

                entity.Property(e => e.Est_Id).HasComment("Indica el identificador único de tbEstados.");

                entity.Property(e => e.Mda_Id).HasComment("Indica el identificador único de la tbModalidades.");

                entity.Property(e => e.Niv_Id).HasComment("Indica el identificador único de tbNivelesEducativos.");

                entity.Property(e => e.Per_Id).HasComment("Indica el identificador único de la tbPersonas.");

                entity.Property(e => e.PromedioAnual)
                    .HasColumnType("decimal(10, 2)")
                    .HasComment("Promedio anual del alumno.");

                entity.Property(e => e.Sec_Id).HasComment("Identificador unico de tbSecciones.");

                entity.HasOne(d => d.Cun)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Cun_Id);

                entity.HasOne(d => d.Cur)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Cur_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbAlumnos_tbCursos_Cur_Id");

                entity.HasOne(d => d.Est)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Est_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbAlumnos_tbEstados_Est_Id");

                entity.HasOne(d => d.Mda)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Mda_Id);

                entity.HasOne(d => d.Niv)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Niv_Id);

                entity.HasOne(d => d.Per)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Per_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbAlumnos_tbPersonas_Per_Id");

                entity.HasOne(d => d.Sec)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Sec_Id);
            });

            modelBuilder.Entity<tbAlumnosHistorial>(entity =>
            {
                entity.HasKey(e => e.AluHistorialId);

                entity.ToTable("tbAlumnosHistorial", "bitacoras");

                entity.Property(e => e.AnioCursado).HasComment("Año en que se cursó el ciclo.");

                entity.Property(e => e.Cun_Id).HasComment("Indica el identificador único de tbCursoNiveles.");

                entity.Property(e => e.Cur_Id).HasComment("Indica el identificador único de tbCursos.");

                entity.Property(e => e.Est_Id).HasComment("Indica el identificador único de tbEstados.");

                entity.Property(e => e.Mda_Id).HasComment("Indica el identificador único de la tbModalidades.");

                entity.Property(e => e.Niv_Id).HasComment("Indica el identificador único de tbNivelesEducativos.");

                entity.Property(e => e.Per_Id).HasComment("Indica el identificador único de la tbPersonas.");

                entity.Property(e => e.PromedioAnual)
                    .HasColumnType("decimal(10, 2)")
                    .HasComment("Promedio anual del alumno.");

                entity.Property(e => e.Sec_Id).HasComment("Identificador unico de tbSecciones.");
            });

            modelBuilder.Entity<tbAulas>(entity =>
            {
                entity.HasKey(e => e.Aul_Id)
                    .HasName("PK__tbAulas__A8EA7F0AA603178A");

                entity.ToTable("tbAulas", "app");

                entity.HasComment("Registra los nombres que contendrá un aula.");

                entity.Property(e => e.Aul_Id).HasComment("Identificador único de la tabla tbAulas.");

                entity.Property(e => e.Aul_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Información de la aula.");

                entity.Property(e => e.Aul_EsEliminado).HasComment("Indica si el aula ha sido eliminada (1) o no (0).\r\n");

                entity.Property(e => e.Aul_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del aula.");

                entity.Property(e => e.Aul_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del aula.\r\n");

                entity.Property(e => e.Aul_UsuarioModifica).HasComment("Identificador del usuario que modificó el aula.\r\n");

                entity.Property(e => e.Aul_UsuarioRegistra).HasComment("Identificador del usuario que registró el aula.\r\n");

                entity.HasOne(d => d.Aul_UsuarioModificaNavigation)
                    .WithMany(p => p.tbAulasAul_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Aul_UsuarioModifica);

                entity.HasOne(d => d.Aul_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbAulasAul_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Aul_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbCargos>(entity =>
            {
                entity.HasKey(e => e.Car_Id)
                    .HasName("PK__tbCargos__523653F936D31E60");

                entity.ToTable("tbCargos", "app");

                entity.HasComment("Registra los puestos que puede tener un empleado en el colegio.");

                entity.Property(e => e.Car_Id).HasComment("Identificador único del puesto.");

                entity.Property(e => e.Car_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Dato informativo del cargo.");

                entity.Property(e => e.Car_EsEliminado).HasComment("Indica si el cargo ha sido eliminado (1) o no (0).\r\n");

                entity.Property(e => e.Car_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del cargo.");

                entity.Property(e => e.Car_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del cargo.\r\n");

                entity.Property(e => e.Car_UsuarioModifica).HasComment("Identificador del usuario que modificó el cargo.\r\n");

                entity.Property(e => e.Car_UsuarioRegistra).HasComment("Identificador del usuario que registró el cargo.\r\n");

                entity.HasOne(d => d.Car_UsuarioModificaNavigation)
                    .WithMany(p => p.tbCargosCar_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Car_UsuarioModifica);

                entity.HasOne(d => d.Car_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbCargosCar_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Car_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbConceptosPago>(entity =>
            {
                entity.HasKey(e => e.Cpa_Id)
                    .HasName("PK__tbConcep__C53A5CC86FE99E31");

                entity.ToTable("tbConceptosPago", "finanza");

                entity.Property(e => e.Cpa_Descripcion)
                    .IsRequired()
                    .HasMaxLength(120);

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");
            });

            modelBuilder.Entity<tbCuentasCobrar>(entity =>
            {
                entity.HasKey(e => e.Cco_Id)
                    .HasName("PK__tbCuenta__EEAE7D0975135D6A");

                entity.ToTable("tbCuentasCobrar", "finanza");

                entity.HasIndex(e => new { e.Alu_Id, e.Epa_Id }, "IX_tbCuentasCobrar_AlumnoEstado");

                entity.Property(e => e.Cco_FechaEmision).HasColumnType("date");

                entity.Property(e => e.Cco_FechaVencimiento).HasColumnType("date");

                entity.Property(e => e.Cco_MontoDescuento).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Cco_MontoMora).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Cco_MontoOriginal).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Cco_MontoPendiente).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Cco_MontoTotal).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Cco_Observaciones).HasMaxLength(300);

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.HasOne(d => d.Cpa)
                    .WithMany(p => p.tbCuentasCobrar)
                    .HasForeignKey(d => d.Cpa_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbCuentasCobrar_tbConceptosPago");

                entity.HasOne(d => d.Epa)
                    .WithMany(p => p.tbCuentasCobrar)
                    .HasForeignKey(d => d.Epa_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbCuentasCobrar_tbEstadosPago");

                entity.HasOne(d => d.Tar)
                    .WithMany(p => p.tbCuentasCobrar)
                    .HasForeignKey(d => d.Tar_Id)
                    .HasConstraintName("FK_tbCuentasCobrar_tbTarifas");
            });

            modelBuilder.Entity<tbCuentasCobrarHistorial>(entity =>
            {
                entity.HasKey(e => e.Cgh_Id)
                    .HasName("PK__tbCuenta__5B76F021A6D6E7DA");

                entity.ToTable("tbCuentasCobrarHistorial", "finanza");

                entity.Property(e => e.Cgh_Accion)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Cgh_Detalle).HasMaxLength(400);

                entity.Property(e => e.Cgh_Fecha)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");
            });

            modelBuilder.Entity<tbCursos>(entity =>
            {
                entity.HasKey(e => e.Cur_Id)
                    .HasName("PK__tbCursos__A20112078864BA0E");

                entity.ToTable("tbCursos", "app");

                entity.HasComment("Administra la información de los cursos.");

                entity.Property(e => e.Cur_Id).HasComment("Identificador único del registro en la tabla.");

                entity.Property(e => e.Cur_EsActivo).HasComment("Estado en el que se encuentra el curso.");

                entity.Property(e => e.Cur_EsEliminado).HasComment("Indica si el curso ha sido eliminado (1) o no (0).\r\n");

                entity.Property(e => e.Cur_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del curso.");

                entity.Property(e => e.Cur_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del curso.\r\n");

                entity.Property(e => e.Cur_Nombre)
                    .HasMaxLength(50)
                    .HasComment("Identificador de un nombre en el curso.");

                entity.Property(e => e.Cur_UsuarioModifica).HasComment("Identificador del usuario que modificó el curso.\r\n");

                entity.Property(e => e.Cur_UsuarioRegistra).HasComment("Identificador del usuario que registró el curso.\r\n");

                entity.Property(e => e.Niv_Id).HasComment("Identificador unico de la tabla tbNivelesEducativos.");

                entity.HasOne(d => d.Cur_UsuarioModificaNavigation)
                    .WithMany(p => p.tbCursosCur_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Cur_UsuarioModifica);

                entity.HasOne(d => d.Cur_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbCursosCur_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Cur_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Niv)
                    .WithMany(p => p.tbCursos)
                    .HasForeignKey(d => d.Niv_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbCursos_tbNivelesEducativos_Niv_Id");

                entity.HasMany(d => d.Cun)
                    .WithMany(p => p.Cur)
                    .UsingEntity<Dictionary<string, object>>(
                        "tbCursos_tbCursosNiveles",
                        l => l.HasOne<tbCursosNiveles>().WithMany().HasForeignKey("Cun_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        r => r.HasOne<tbCursos>().WithMany().HasForeignKey("Cur_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        j =>
                        {
                            j.HasKey("Cur_Id", "Cun_Id").HasName("PK_tbCursos_tbCursosNiveles_Cur_Id_Cun_Id");

                            j.ToTable("tbCursos_tbCursosNiveles", "app");

                            j.IndexerProperty<int>("Cur_Id").HasComment("Identificador único del curso.\r\n");

                            j.IndexerProperty<int>("Cun_Id").HasComment("Identificador único en el nivel del curso.\r\n");
                        });

                entity.HasMany(d => d.Mat)
                    .WithMany(p => p.Cur)
                    .UsingEntity<Dictionary<string, object>>(
                        "tbCursos_tbMaterias",
                        l => l.HasOne<tbMaterias>().WithMany().HasForeignKey("Mat_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        r => r.HasOne<tbCursos>().WithMany().HasForeignKey("Cur_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        j =>
                        {
                            j.HasKey("Cur_Id", "Mat_Id").HasName("PK__tbCursos__DA4C9500E99A4553");

                            j.ToTable("tbCursos_tbMaterias", "app").HasComment("Registra las materias que están asignadas a un curso.");
                        });

                entity.HasMany(d => d.Mda)
                    .WithMany(p => p.Cur)
                    .UsingEntity<Dictionary<string, object>>(
                        "tbCursos_tbModalidades",
                        l => l.HasOne<tbModalidades>().WithMany().HasForeignKey("Mda_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        r => r.HasOne<tbCursos>().WithMany().HasForeignKey("Cur_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        j =>
                        {
                            j.HasKey("Cur_Id", "Mda_Id").HasName("PK_tbCursos_tbModalidades_Cur_Id_Mda_Id");

                            j.ToTable("tbCursos_tbModalidades", "app");
                        });
            });

            modelBuilder.Entity<tbCursosHistorial>(entity =>
            {
                entity.HasKey(e => e.Cur_Id)
                    .HasName("PK__tbCursos__A20112079B9A41A6");

                entity.ToTable("tbCursosHistorial", "bitacoras");

                entity.Property(e => e.Accion)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Cno_Id).HasComment("");

                entity.Property(e => e.EsActivo).HasDefaultValueSql("((1))");

                entity.Property(e => e.EsEliminado).HasDefaultValueSql("((0))");

                entity.Property(e => e.Fecha).HasColumnType("datetime");

                entity.Property(e => e.HostName)
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Usuario)
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbCursosNiveles>(entity =>
            {
                entity.HasKey(e => e.Cun_Id);

                entity.ToTable("tbCursosNiveles", "app");

                entity.HasComment("Administra el nivel educativo que tendrá un curso.");

                entity.Property(e => e.Cun_Id).HasComment("Identificador único de la tabla tbCursosNiveles.");

                entity.Property(e => e.Cun_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("Información del curso nivel.");

                entity.Property(e => e.Cun_FechaModifica).HasColumnType("datetime");

                entity.Property(e => e.Cun_FechaRegistra).HasColumnType("datetime");

                entity.Property(e => e.Niv_Id).HasComment("Identificador del nivel del curso.");

                entity.HasOne(d => d.Niv)
                    .WithMany(p => p.tbCursosNiveles)
                    .HasForeignKey(d => d.Niv_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbCursos_tbSecciones>(entity =>
            {
                entity.HasKey(e => new { e.Cur_Id, e.Sec_Id })
                    .HasName("PK_tbCursos_tbSecciones_Cur_Id_Sec_Id");

                entity.ToTable("tbCursos_tbSecciones", "app");

                entity.HasOne(d => d.Aul)
                    .WithMany(p => p.tbCursos_tbSecciones)
                    .HasForeignKey(d => d.Aul_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Cur)
                    .WithMany(p => p.tbCursos_tbSecciones)
                    .HasForeignKey(d => d.Cur_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Sec)
                    .WithMany(p => p.tbCursos_tbSecciones)
                    .HasForeignKey(d => d.Sec_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbDepartamentoEmpleados>(entity =>
            {
                entity.HasKey(e => e.Dep_Id);

                entity.ToTable("tbDepartamentoEmpleados", "app");

                entity.Property(e => e.Dep_Id).HasComment("Identificador único del departamento.\r\n");

                entity.Property(e => e.Nombre)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("Nombre del departamento.");
            });

            modelBuilder.Entity<tbDescuentos>(entity =>
            {
                entity.HasKey(e => e.Des_Id)
                    .HasName("PK__tbDescue__EC5445EAABA1E1EB");

                entity.ToTable("tbDescuentos", "finanza");

                entity.Property(e => e.Des_Descripcion)
                    .IsRequired()
                    .HasMaxLength(120);

                entity.Property(e => e.Des_TipoDescuento)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Des_Valor).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");
            });

            modelBuilder.Entity<tbDescuentosAplicados>(entity =>
            {
                entity.HasKey(e => e.Dap_Id)
                    .HasName("PK__tbDescue__4EB1F1CC3932997E");

                entity.ToTable("tbDescuentosAplicados", "finanza");

                entity.Property(e => e.Dap_Justificacion).HasMaxLength(300);

                entity.Property(e => e.Dap_MontoAplicado).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.HasOne(d => d.Cco)
                    .WithMany(p => p.tbDescuentosAplicados)
                    .HasForeignKey(d => d.Cco_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbDescuentosAplicados_tbCuentasCobrar");

                entity.HasOne(d => d.Des)
                    .WithMany(p => p.tbDescuentosAplicados)
                    .HasForeignKey(d => d.Des_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbDescuentosAplicados_tbDescuentos");
            });

            modelBuilder.Entity<tbDias>(entity =>
            {
                entity.HasKey(e => e.Dia_Id)
                    .HasName("PK__tbDias__4861F1C96D175608");

                entity.ToTable("tbDias", "app");

                entity.HasComment("Registra los días laborales.");

                entity.Property(e => e.Dia_Id).HasComment("Identificador único de los dias.");

                entity.Property(e => e.Dia_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Nombre del dia.");

                entity.Property(e => e.Dia_EsEliminado).HasComment("Indica si el día ha sido eliminado (1) o no (0).\r\n");

                entity.Property(e => e.Dia_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del día.");

                entity.Property(e => e.Dia_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del día.\r\n");

                entity.Property(e => e.Dia_UsuarioModifica).HasComment("Identificador del usuario que modificó el día.\r\n");

                entity.Property(e => e.Dia_UsuarioRegistra).HasComment("Identificador del usuario que registró el día.\r\n");

                entity.HasOne(d => d.Dia_UsuarioModificaNavigation)
                    .WithMany(p => p.tbDiasDia_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Dia_UsuarioModifica);

                entity.HasOne(d => d.Dia_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbDiasDia_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Dia_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbDuraciones>(entity =>
            {
                entity.HasKey(e => e.Dur_Id)
                    .HasName("PK__tbDuraci__CC0C30B7B6F3CA5B");

                entity.ToTable("tbDuraciones", "app");

                entity.HasComment("Registra las diferentes duraciones que puede tener una materia.");

                entity.Property(e => e.Dur_Id).HasComment("Identificador único de la duracion.");

                entity.Property(e => e.Dur_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Información del tiempo designado para una materia.");

                entity.Property(e => e.Dur_EsEliminado).HasComment("Indica si la duración ha sido eliminada (1) o no (0).\r\n");

                entity.Property(e => e.Dur_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación de la duración.");

                entity.Property(e => e.Dur_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro de la duración.\r\n");

                entity.Property(e => e.Dur_UsuarioModifica).HasComment("Identificador del usuario que modificó la duración.\r\n");

                entity.Property(e => e.Dur_UsuarioRegistra).HasComment("Identificador del usuario que registró la duración.\r\n");

                entity.HasOne(d => d.Dur_UsuarioModificaNavigation)
                    .WithMany(p => p.tbDuracionesDur_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Dur_UsuarioModifica);

                entity.HasOne(d => d.Dur_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbDuracionesDur_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Dur_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbEmpleados>(entity =>
            {
                entity.HasKey(e => e.Emp_Id)
                    .HasName("PK__tbEmplea__262359AB8C82E674");

                entity.ToTable("tbEmpleados", "app");

                entity.HasComment("Guarda la información relacionada con el personal que labora en la empresa.");

                entity.HasIndex(e => e.Emp_Codigo, "UQ__tbEmplea__DA75CA5FD51409D0")
                    .IsUnique();

                entity.Property(e => e.Emp_Id).HasComment("Identificador único de la tabla tbEmpleados.");

                entity.Property(e => e.Car_Id).HasComment("Identificador de la tabla tbCargos. ");

                entity.Property(e => e.Dep_Id).HasComment("Identificador único del departamento de empleados.");

                entity.Property(e => e.Emp_Codigo)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("Codigo numerico que identifica a tbEmpleados.");

                entity.Property(e => e.Per_Id).HasComment("Identificador de tbPersonas.");

                entity.Property(e => e.Tit_Id).HasComment("Identificador de la tabla tbTitulos.");

                entity.HasOne(d => d.Car)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Car_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbEmpleados_tbCargos_Car_Id");

                entity.HasOne(d => d.Dep)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Dep_Id)
                    .HasConstraintName("FK_tbEmpleados_tbEmpleados_Dep_Id");

                entity.HasOne(d => d.Per)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Per_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbEmpleados_tbPersonas_Per_Id");

                entity.HasOne(d => d.Tit)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Tit_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbEmpleados_tbTitulos_Tit_Id");

                entity.HasMany(d => d.Mat)
                    .WithMany(p => p.Emp)
                    .UsingEntity<Dictionary<string, object>>(
                        "tbEmpleados_tbMaterias",
                        l => l.HasOne<tbMaterias>().WithMany().HasForeignKey("Mat_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        r => r.HasOne<tbEmpleados>().WithMany().HasForeignKey("Emp_Id").OnDelete(DeleteBehavior.ClientSetNull),
                        j =>
                        {
                            j.HasKey("Emp_Id", "Mat_Id").HasName("PK__tbEmplea__5E6EDEAC54CE7532");

                            j.ToTable("tbEmpleados_tbMaterias", "app").HasComment("Guarda las materias que tiene asignado un alumno.");

                            j.IndexerProperty<int>("Emp_Id").HasComment("Identificador único de los empleados.\r\n");

                            j.IndexerProperty<int>("Mat_Id").HasComment("Identificador único de la materia.");
                        });
            });

            modelBuilder.Entity<tbEncargados>(entity =>
            {
                entity.HasKey(e => e.Enc_Id)
                    .HasName("PK__tbEncarg__016143D5884C95F9");

                entity.ToTable("tbEncargados", "app");

                entity.HasComment("Registra los datos del representante del alumno.");

                entity.Property(e => e.Enc_Id).HasComment("Identificador único de un encargado.");

                entity.Property(e => e.Enc_Ocupacion)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("Trabajo que desempeña el padre del alumno.");

                entity.Property(e => e.Per_Id).HasComment("Identificador de la persona.");

                entity.HasOne(d => d.Per)
                    .WithMany(p => p.tbEncargados)
                    .HasForeignKey(d => d.Per_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbEncargados_tbPersonas_Per_Id");
            });

            modelBuilder.Entity<tbEncargadosHistorial>(entity =>
            {
                entity.HasKey(e => e.Enc_Id)
                    .HasName("PK__tbEncarg__016143D55057401C");

                entity.ToTable("tbEncargadosHistorial", "bitacoras");

                entity.Property(e => e.Accion)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.EsActivo).HasDefaultValueSql("((1))");

                entity.Property(e => e.EsEliminado).HasDefaultValueSql("((0))");

                entity.Property(e => e.Fecha).HasColumnType("datetime");

                entity.Property(e => e.HostName)
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Usuario)
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbEncargados_tbAlumnos>(entity =>
            {
                entity.HasKey(e => new { e.Enc_Id, e.Alu_Id })
                    .HasName("PK__tbEncarg__90D2CA92AB2DC226");

                entity.ToTable("tbEncargados_tbAlumnos", "app");

                entity.HasComment("Contiene los encargados relacionados con el alumno.");

                entity.Property(e => e.Enc_Id).HasComment("Identificador único del encargado.");

                entity.Property(e => e.Alu_Id).HasComment("Identificador único del alumno.");

                entity.Property(e => e.Par_Id).HasComment("Identificador único del parcial.");

                entity.HasOne(d => d.Alu)
                    .WithMany(p => p.tbEncargados_tbAlumnos)
                    .HasForeignKey(d => d.Alu_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Enc)
                    .WithMany(p => p.tbEncargados_tbAlumnos)
                    .HasForeignKey(d => d.Enc_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Par)
                    .WithMany(p => p.tbEncargados_tbAlumnos)
                    .HasForeignKey(d => d.Par_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbEstados>(entity =>
            {
                entity.HasKey(e => e.Est_Id)
                    .HasName("PK__tbEstado__345473BCA87AB9A5");

                entity.ToTable("tbEstados", "app");

                entity.HasComment("Indica en que estado se encuentra el alumno, activo o inactivo.");

                entity.Property(e => e.Est_Id).HasComment("Identificador único de un estado.");

                entity.Property(e => e.Est_Descripcion)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Información del estado actual del alumno en el instituto.");

                entity.Property(e => e.Est_EsEliminado).HasComment("Indica si el estado ha sido eliminado (1) o no (0).\r\n");

                entity.Property(e => e.Est_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del estado.");

                entity.Property(e => e.Est_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del estado.");

                entity.Property(e => e.Est_UsuarioModifica).HasComment("Identificador del usuario que modificó el estado.");

                entity.Property(e => e.Est_UsuarioRegistra).HasComment("Identificador del usuario que registró el estado.");

                entity.HasOne(d => d.Est_UsuarioModificaNavigation)
                    .WithMany(p => p.tbEstadosEst_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Est_UsuarioModifica);

                entity.HasOne(d => d.Est_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbEstadosEst_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Est_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbEstadosPago>(entity =>
            {
                entity.HasKey(e => e.Epa_Id)
                    .HasName("PK__tbEstado__A14223FED72D8E06");

                entity.ToTable("tbEstadosPago", "finanza");

                entity.Property(e => e.Epa_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");
            });

            modelBuilder.Entity<tbFormasPago>(entity =>
            {
                entity.HasKey(e => e.Fpa_Id)
                    .HasName("PK__tbFormas__8A91785725C0E2B9");

                entity.ToTable("tbFormasPago", "finanza");

                entity.Property(e => e.Fpa_Descripcion)
                    .IsRequired()
                    .HasMaxLength(80);

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");
            });

            modelBuilder.Entity<tbHorario>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tbHorario", "app");

                entity.Property(e => e.s)
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            modelBuilder.Entity<tbHorarioAlumnos>(entity =>
            {
                entity.HasKey(e => e.HoAl_Id)
                    .HasName("PK__tbHorari__6D7BA73D0EBF03DA");

                entity.ToTable("tbHorarioAlumnos", "app");

                entity.HasComment("Almacena la hora a la que el alumno recibirá sus clases y recesos.");

                entity.HasIndex(e => new { e.HoAl_Año, e.Sem_Id, e.Sec_Id, e.Dia_Id }, "IX_tbHorarioAlumnos_Año_Sem_Sec_Dia");

                entity.Property(e => e.HoAl_Id).HasComment("Identificador único de la tabla.");

                entity.Property(e => e.Cun_Id).HasComment("Identificador de curso niveles.");

                entity.Property(e => e.Cur_Id).HasComment("Identificador del curso.");

                entity.Property(e => e.Dia_Id)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Identificador del dia.");

                entity.Property(e => e.HoAl_EsEliminado).HasComment("Indica si el horario del alumno ha sido eliminado (1) o no (0).\r\n");

                entity.Property(e => e.HoAl_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del horario del alumno.");

                entity.Property(e => e.HoAl_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del horario del alumno.");

                entity.Property(e => e.HoAl_HoraFinaliza).HasComment("Fecha de finalizacion de las clases.");

                entity.Property(e => e.HoAl_HoraInicio).HasComment("Fecha de inicio de las clases.");

                entity.Property(e => e.HoAl_UsuarioModifica).HasComment("Identificador del usuario que modificó el horario del alumno.");

                entity.Property(e => e.HoAl_UsuarioRegistra).HasComment("Identificador del usuario que registró el horario del alumno.");

                entity.Property(e => e.Mat_Id).HasComment("Identificador de la materia.");

                entity.HasOne(d => d.Aul)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Aul_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Cun)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Cun_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Dia)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Dia_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbHorarioAlumnos_tbDias_Dia_Id");

                entity.HasOne(d => d.Emp)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Emp_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.HoAl_HoraFinalizaNavigation)
                    .WithMany(p => p.tbHorarioAlumnosHoAl_HoraFinalizaNavigation)
                    .HasForeignKey(d => d.HoAl_HoraFinaliza)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.HoAl_HoraInicioNavigation)
                    .WithMany(p => p.tbHorarioAlumnosHoAl_HoraInicioNavigation)
                    .HasForeignKey(d => d.HoAl_HoraInicio)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.HoAl_UsuarioModificaNavigation)
                    .WithMany(p => p.tbHorarioAlumnosHoAl_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.HoAl_UsuarioModifica)
                    .HasConstraintName("FK_tbHorarioAlumnos_tbUsuarios_Cur_UsuarioModifica");

                entity.HasOne(d => d.HoAl_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbHorarioAlumnosHoAl_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.HoAl_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbHorarioAlumnos_tbUsuarios_Cur_UsuarioRegistra");

                entity.HasOne(d => d.Mat)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Mat_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Mda)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Mda_Id);

                entity.HasOne(d => d.Sec)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Sec_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Sem)
                    .WithMany(p => p.tbHorarioAlumnos)
                    .HasForeignKey(d => d.Sem_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbHorarioAlumnosHistorial>(entity =>
            {
                entity.HasKey(e => e.HoAl_Id)
                    .HasName("PK__tbHorari__6D7BA73DA5AFF29B");

                entity.ToTable("tbHorarioAlumnosHistorial", "bitacoras");

                entity.Property(e => e.Accion)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.EsEliminado).HasDefaultValueSql("((0))");

                entity.Property(e => e.Fecha).HasColumnType("datetime");

                entity.Property(e => e.HostName)
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Usuario)
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbHorarioProfesores>(entity =>
            {
                entity.HasKey(e => e.HoPr_Id)
                    .HasName("PK__tbHorari__EA2890DFE689A6EA");

                entity.ToTable("tbHorarioProfesores", "app");

                entity.HasComment("Almacena la hora a la que el profesor dará sus clases y recesos.");

                entity.HasIndex(e => new { e.HoPr_Año, e.Sem_Id, e.Emp_Id, e.Dia_Id }, "IX_tbHorarioProfesores_Año_Sem_Emp_Dia");

                entity.Property(e => e.HoPr_Id).HasComment("Identificador único de cada hora.");

                entity.Property(e => e.Cun_Id).HasComment("Identificador del curso.");

                entity.Property(e => e.Cur_Id).HasComment("Identificador del curso.");

                entity.Property(e => e.Dia_Id)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Identificador único.");

                entity.Property(e => e.HoPr_EsEliminado).HasComment("Indica si el horario del profesor ha sido eliminado (1) o no (0).\r\n");

                entity.Property(e => e.HoPr_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del horario del profesor.");

                entity.Property(e => e.HoPr_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del horario del profesor.\r\n");

                entity.Property(e => e.HoPr_HoraFinaliza).HasComment("Hora a la que finaliza.");

                entity.Property(e => e.HoPr_HoraInicio).HasComment("Hora a la que inicia.");

                entity.Property(e => e.HoPr_UsuarioModifica).HasComment("Identificador del usuario que modificó el horario del profesor.\r\n");

                entity.Property(e => e.HoPr_UsuarioRegistra).HasComment("Identificador del usuario que registró el horario del profesor.\r\n");

                entity.HasOne(d => d.Aul)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Aul_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Cun)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Cun_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Cur)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Cur_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbHorarioProfesores_tbCursos_Cur_Id");

                entity.HasOne(d => d.Dia)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Dia_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbHorarioProfesores_tbDias_Dia_Id");

                entity.HasOne(d => d.Emp)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Emp_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.HoPr_HoraFinalizaNavigation)
                    .WithMany(p => p.tbHorarioProfesoresHoPr_HoraFinalizaNavigation)
                    .HasForeignKey(d => d.HoPr_HoraFinaliza)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.HoPr_HoraInicioNavigation)
                    .WithMany(p => p.tbHorarioProfesoresHoPr_HoraInicioNavigation)
                    .HasForeignKey(d => d.HoPr_HoraInicio)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Mat)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Mat_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Mda)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Mda_Id);

                entity.HasOne(d => d.Sec)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Sec_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Sem)
                    .WithMany(p => p.tbHorarioProfesores)
                    .HasForeignKey(d => d.Sem_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbHoras>(entity =>
            {
                entity.HasKey(e => e.Hor_Id);

                entity.ToTable("tbHoras", "app");

                entity.HasComment("Administra las horas de labor diaria.");

                entity.Property(e => e.Hor_Id).HasComment("Identificador único de la hora.");

                entity.Property(e => e.Hor_EsEliminado).HasComment("Indica si la hora ha sido eliminada (1) o no (0).");

                entity.Property(e => e.Hor_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación de la hora.");

                entity.Property(e => e.Hor_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro de la hora.");

                entity.Property(e => e.Hor_Hora)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .HasComment("Descripción de la hora indicada.");

                entity.Property(e => e.Hor_UsuarioModifica).HasComment("Identificador del usuario que modificó la hora.");

                entity.Property(e => e.Hor_UsuarioRegistra).HasComment("Identificador del usuario que registró la hora.");
            });

            modelBuilder.Entity<tbMaterias>(entity =>
            {
                entity.HasKey(e => e.Mat_Id)
                    .HasName("PK__tbMateri__84D87076DF7CBB78");

                entity.ToTable("tbMaterias", "app");

                entity.HasComment("Materia que puede impartir un profesor o recibir el alumno.");

                entity.Property(e => e.Mat_Id).HasComment("Identificador único de la materia.");

                entity.Property(e => e.Dur_Id).HasComment("Identificador de la duración.");

                entity.Property(e => e.Mat_EsActivo).HasComment("Valor que indica si este registro sera visible.");

                entity.Property(e => e.Mat_EsEliminado).HasComment("Indica si la materia ha sido eliminada (1) o no (0).");

                entity.Property(e => e.Mat_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación de la materia.");

                entity.Property(e => e.Mat_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro de la materia.");

                entity.Property(e => e.Mat_Nombre)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasComment("Nombre por el cual es distinguida la materia.");

                entity.Property(e => e.Mat_UsuarioModifica).HasComment("Identificador del usuario que modificó la materia.");

                entity.Property(e => e.Mat_UsuarioRegistra).HasComment("Identificador del usuario que registró la materia.");

                entity.HasOne(d => d.Dur)
                    .WithMany(p => p.tbMaterias)
                    .HasForeignKey(d => d.Dur_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbMaterias_tbDuraciones_Dur_Id");

                entity.HasOne(d => d.Mat_UsuarioModificaNavigation)
                    .WithMany(p => p.tbMateriasMat_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Mat_UsuarioModifica);

                entity.HasOne(d => d.Mat_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbMateriasMat_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Mat_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbMateriasHistorial>(entity =>
            {
                entity.HasKey(e => e.Mat_Id)
                    .HasName("PK__tbMateri__84D87076FEF4A9EE");

                entity.ToTable("tbMateriasHistorial", "bitacoras");

                entity.Property(e => e.Accion)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.EsActivo).HasDefaultValueSql("((1))");

                entity.Property(e => e.EsEliminado).HasDefaultValueSql("((0))");

                entity.Property(e => e.Fecha).HasColumnType("datetime");

                entity.Property(e => e.HostName)
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Mat_Nombre)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Usuario)
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbMatriculas>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tbMatriculas", "app");

                entity.Property(e => e.Alu_Id).HasComment("Identificador único del alumno.");

                entity.Property(e => e.Matri_Id).HasComment("Identificador único de la matricula.");
            });

            modelBuilder.Entity<tbModalidades>(entity =>
            {
                entity.HasKey(e => e.Mda_Id)
                    .HasName("PK__tbModali__C564EC281C06B8EB");

                entity.ToTable("tbModalidades", "app");

                entity.HasComment("Especifica las diferentes modalidades en que pueden impartirse clases, estos son horas determinadas en la semana para que los alumnos asistan a clases.");

                entity.Property(e => e.Mda_Id).HasComment("Identificador único de la modalidad.");

                entity.Property(e => e.Mda_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("Descripción por el cual se conoce la modalidad.");

                entity.Property(e => e.Mda_EsEliminado).HasComment("Indica si la modalidad ha sido eliminada (1) o no (0).");

                entity.Property(e => e.Mda_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación de la modalidad.");

                entity.Property(e => e.Mda_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro de la modalidad.");

                entity.Property(e => e.Mda_UsuarioModifica).HasComment("Identificador del usuario que modificó la modalidad.");

                entity.Property(e => e.Mda_UsuarioRegistra).HasComment("Identificador del usuario que registró la modalidad.");

                entity.HasOne(d => d.Mda_UsuarioModificaNavigation)
                    .WithMany(p => p.tbModalidadesMda_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Mda_UsuarioModifica)
                    .HasConstraintName("FK_tbModalidades_tbUsuarios_mda_UsuarioModifica");

                entity.HasOne(d => d.Mda_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbModalidadesMda_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Mda_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbModalidades_tbUsuarios_mda_UsuarioRegistra");

                entity.HasMany(d => d.Cun)
                    .WithMany(p => p.Mda)
                    .UsingEntity<Dictionary<string, object>>(
                        "tbModalidades_tbCursosNiveles",
                        l => l.HasOne<tbCursosNiveles>().WithMany().HasForeignKey("Cun_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_tbCursosNiveles_tbModalidades_tbCursosNiveles_Cun_Id"),
                        r => r.HasOne<tbModalidades>().WithMany().HasForeignKey("Mda_Id").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_tbCursosNiveles_tbModalidades_tbModalidades_Mda_Id"),
                        j =>
                        {
                            j.HasKey("Mda_Id", "Cun_Id").HasName("PK_tbCursosNiveles_tbModalidades_Mda_Id_Cun_Id");

                            j.ToTable("tbModalidades_tbCursosNiveles", "app");

                            j.IndexerProperty<int>("Mda_Id").HasComment("Identificador único de la modalidad.");

                            j.IndexerProperty<int>("Cun_Id").HasComment("Identificador único de curso niveles.");
                        });
            });

            modelBuilder.Entity<tbMoratorias>(entity =>
            {
                entity.HasKey(e => e.Mor_Id)
                    .HasName("PK__tbMorato__E06D203F9D05219D");

                entity.ToTable("tbMoratorias", "finanza");

                entity.Property(e => e.Mor_FechaCalculo).HasColumnType("date");

                entity.Property(e => e.Mor_MontoMora).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Mor_Porcentaje).HasColumnType("decimal(9, 4)");

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.HasOne(d => d.Cco)
                    .WithMany(p => p.tbMoratorias)
                    .HasForeignKey(d => d.Cco_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbMoratorias_tbCuentasCobrar");
            });

            modelBuilder.Entity<tbNivelesEducativos>(entity =>
            {
                entity.HasKey(e => e.Niv_Id)
                    .HasName("PK__tbNivele__F0ED3B984C55F272");

                entity.ToTable("tbNivelesEducativos", "app");

                entity.HasComment("Estos son los niveles de educación con los que se cuenta, en cada nivel se culmina un ciclo para el alumno.");

                entity.Property(e => e.Niv_Id).HasComment("Identificador único de un nivel educativo.");

                entity.Property(e => e.Niv_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("Información de el nivel del alumno.");

                entity.Property(e => e.Niv_EsActivo).HasComment("Indica si el nivel educativo está activo (1) o no (0).");

                entity.Property(e => e.Niv_EsEliminado).HasComment("Indica si el nivel educativo ha sido eliminado (1) o no (0).");

                entity.Property(e => e.Niv_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del nivel educativo.");

                entity.Property(e => e.Niv_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del nivel educativo.");

                entity.Property(e => e.Niv_UsuarioModifica).HasComment("Identificador del usuario que modificó el nivel educativo.");

                entity.Property(e => e.Niv_UsuarioRegistra).HasComment("Identificador del usuario que registró el nivel educativo.");

                entity.HasOne(d => d.Niv_UsuarioModificaNavigation)
                    .WithMany(p => p.tbNivelesEducativosNiv_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Niv_UsuarioModifica);

                entity.HasOne(d => d.Niv_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbNivelesEducativosNiv_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Niv_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbNotas>(entity =>
            {
                entity.HasKey(e => e.Not_Id)
                    .HasName("PK__tbNotas__EEB6CF8840083E33");

                entity.ToTable("tbNotas", "app");

                entity.HasComment("Define las notas de cada alumno.");

                entity.Property(e => e.Not_Id).HasComment("Identificador único de la tabla.");

                entity.Property(e => e.Alu_Id).HasComment("Información sobre la nota dada al alumno.");

                entity.Property(e => e.Aul_Id).HasComment("Información sobre la nota dada al alumno.");

                entity.Property(e => e.Mat_Id).HasComment("Identificador de la tabla tbMaterias.");

                entity.Property(e => e.Not_Año)
                    .HasColumnType("date")
                    .HasComment("Año en el que se aplico la nota.");

                entity.Property(e => e.Not_EsActivo).HasComment("Estado de la nota.");

                entity.Property(e => e.Not_EsEliminado).HasComment("Indica si la nota ha sido eliminada (1) o no (0).");

                entity.Property(e => e.Not_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación de la nota.");

                entity.Property(e => e.Not_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro de la nota.");

                entity.Property(e => e.Not_Nota).HasComment("Información sobre la nota dada al alumno.");

                entity.Property(e => e.Not_UsuarioModifica).HasComment("Identificador del usuario que modificó la nota.");

                entity.Property(e => e.Not_UsuarioRegistra).HasComment("Identificador del usuario que registró la nota.");

                entity.Property(e => e.Pac_Id).HasComment("Identificador único de la tabla tbParciales.");

                entity.Property(e => e.Sec_Id).HasComment("Información sobre la nota dada al alumno.");

                entity.Property(e => e.Sem_Id).HasComment("Identificador único de la tabla tbSemestres.");

                entity.HasOne(d => d.Mat)
                    .WithMany(p => p.tbNotas)
                    .HasForeignKey(d => d.Mat_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbNotas_tbMaterias_Mat_Id");

                entity.HasOne(d => d.Not_UsuarioModificaNavigation)
                    .WithMany(p => p.tbNotasNot_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Not_UsuarioModifica);

                entity.HasOne(d => d.Not_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbNotasNot_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Not_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Pac)
                    .WithMany(p => p.tbNotas)
                    .HasForeignKey(d => d.Pac_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Sem)
                    .WithMany(p => p.tbNotas)
                    .HasForeignKey(d => d.Sem_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("tbNotas_tbSemestres_Sem_Id");
            });

            modelBuilder.Entity<tbNotasHistorial>(entity =>
            {
                entity.HasKey(e => e.Not_Id)
                    .HasName("PK__tbNotasH__EEB6CF881138C866");

                entity.ToTable("tbNotasHistorial", "bitacoras");

                entity.Property(e => e.Accion)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.EsActivo).HasDefaultValueSql("((1))");

                entity.Property(e => e.EsEliminado).HasDefaultValueSql("((0))");

                entity.Property(e => e.Fecha).HasColumnType("datetime");

                entity.Property(e => e.HostName)
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Not_Ano).HasColumnType("date");

                entity.Property(e => e.Usuario)
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbPagos>(entity =>
            {
                entity.HasKey(e => e.Pag_Id)
                    .HasName("PK__tbPagos__F4282D1BF078D80F");

                entity.ToTable("tbPagos", "finanza");

                entity.HasIndex(e => e.Pag_FechaPago, "IX_tbPagos_Fecha");

                entity.Property(e => e.Pag_FechaPago).HasPrecision(0);

                entity.Property(e => e.Pag_MontoTotal).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Pag_NumeroReferencia).HasMaxLength(60);

                entity.Property(e => e.Pag_Observaciones).HasMaxLength(300);

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.HasOne(d => d.Fpa)
                    .WithMany(p => p.tbPagos)
                    .HasForeignKey(d => d.Fpa_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbPagos_tbFormasPago");
            });

            modelBuilder.Entity<tbPagosDetalle>(entity =>
            {
                entity.HasKey(e => e.Pde_Id)
                    .HasName("PK__tbPagosD__47B372B9FCEE39EB");

                entity.ToTable("tbPagosDetalle", "finanza");

                entity.Property(e => e.Pde_MontoAplicado).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.HasOne(d => d.Cco)
                    .WithMany(p => p.tbPagosDetalle)
                    .HasForeignKey(d => d.Cco_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbPagosDetalle_tbCuentasCobrar");

                entity.HasOne(d => d.Pag)
                    .WithMany(p => p.tbPagosDetalle)
                    .HasForeignKey(d => d.Pag_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbPagosDetalle_tbPagos");
            });

            modelBuilder.Entity<tbPagosHistorial>(entity =>
            {
                entity.HasKey(e => e.Pgh_Id)
                    .HasName("PK__tbPagosH__5B078FE8F6AFEA59");

                entity.ToTable("tbPagosHistorial", "finanza");

                entity.Property(e => e.Pgh_Accion)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Pgh_Detalle).HasMaxLength(400);

                entity.Property(e => e.Pgh_Fecha)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");
            });

            modelBuilder.Entity<tbParciales>(entity =>
            {
                entity.HasKey(e => e.Pac_Id)
                    .HasName("PK__tbParcia__FD0E433E00746004");

                entity.ToTable("tbParciales", "app");

                entity.HasComment("Indica los parciales que tendrá un semestre");

                entity.Property(e => e.Pac_Id).HasComment("Identificador único del parcial.");

                entity.Property(e => e.Pac_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Información por el cual se conocera el parcial.");

                entity.Property(e => e.Pac_EsEliminado).HasComment("Indica si el parcial ha sido eliminado (1) o no (0).");

                entity.Property(e => e.Pac_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del parcial.");

                entity.Property(e => e.Pac_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del parcial.");

                entity.Property(e => e.Pac_UsuarioModifica).HasComment("Identificador del usuario que modificó el parcial.");

                entity.Property(e => e.Pac_UsuarioRegistra).HasComment("Identificador del usuario que registró el parcial.");

                entity.HasOne(d => d.Pac_UsuarioModificaNavigation)
                    .WithMany(p => p.tbParcialesPac_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Pac_UsuarioModifica);

                entity.HasOne(d => d.Pac_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbParcialesPac_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Pac_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbParentescos>(entity =>
            {
                entity.HasKey(e => e.Par_Id)
                    .HasName("PK__tbParent__620469CEB79C9535");

                entity.ToTable("tbParentescos", "app");

                entity.HasComment("Relación entre el encargado legal y el alumno.");

                entity.Property(e => e.Par_Id).HasComment("Identificador único de un parentesco.");

                entity.Property(e => e.Par_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("Descripción sobre el parentesco sangíneo o no sangíneo del encargado.");

                entity.Property(e => e.Par_EsEliminado).HasComment("Indica si el parentesco ha sido eliminado (1) o no (0).");

                entity.Property(e => e.Par_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del parentesco.");

                entity.Property(e => e.Par_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del parentesco.");

                entity.Property(e => e.Par_UsuarioModifica).HasComment("Identificador del usuario que modificó el parentesco.");

                entity.Property(e => e.Par_UsuarioRegistra).HasComment("Identificador del usuario que registró el parentesco.");

                entity.HasOne(d => d.Par_UsuarioModificaNavigation)
                    .WithMany(p => p.tbParentescosPar_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Par_UsuarioModifica);

                entity.HasOne(d => d.Par_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbParentescosPar_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Par_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbPersonas>(entity =>
            {
                entity.HasKey(e => e.Per_Id)
                    .HasName("PK__tbPerson__2705F940FE026996");

                entity.ToTable("tbPersonas", "app");

                entity.HasComment("Administra los datos de las personas involucradas en el sistema.");

                entity.Property(e => e.Per_Id).HasComment("Indica el identificador único de la persona.");

                entity.Property(e => e.Per_ApellidoMaterno)
                    .HasMaxLength(50)
                    .HasComment("Segundo apellido de la persona.");

                entity.Property(e => e.Per_ApellidoPaterno)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasComment("Primer apellido dado a la persona.");

                entity.Property(e => e.Per_CorreoElectronico)
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasComment("Medio por el cual permite ponerse en contacto mediante mensaje electronico con la persona.");

                entity.Property(e => e.Per_Direccion)
                    .IsRequired()
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasComment("Información sobre una dirección aproximada.");

                entity.Property(e => e.Per_EsActivo).HasComment("Indica el estado actual de la persona.");

                entity.Property(e => e.Per_EsEliminado).HasComment("Indica si la persona ha sido eliminada (1) o no (0).\r\n");

                entity.Property(e => e.Per_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación de la persona.");

                entity.Property(e => e.Per_FechaNacimiento)
                    .HasColumnType("date")
                    .HasComment("Fecha en la que nacio la persona.");

                entity.Property(e => e.Per_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro de la persona.");

                entity.Property(e => e.Per_Identidad)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasComment("Serie de digitos dado por el registro nacional para distingir únicamente a una persona.");

                entity.Property(e => e.Per_Imagen)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("Serie de digitos dado por el registro nacional para distingir únicamente a una persona.");

                entity.Property(e => e.Per_PrimerNombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasComment("Primer nombre de la persona.");

                entity.Property(e => e.Per_SegundoNombre)
                    .HasMaxLength(50)
                    .HasComment("Segundo nombre de la persona.");

                entity.Property(e => e.Per_Sexo)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasComment("Indica el sexo de la persona.");

                entity.Property(e => e.Per_Telefono)
                    .IsRequired()
                    .HasMaxLength(9)
                    .IsUnicode(false)
                    .HasComment("Almacena una serie de digitos de teléfono.");

                entity.Property(e => e.Per_UsuarioModifica).HasComment("Identificador del usuario que modificó la persona.");

                entity.Property(e => e.Per_UsuarioRegistra).HasComment("Identificador del usuario que registró la persona.");

                entity.HasOne(d => d.Per_UsuarioModificaNavigation)
                    .WithMany(p => p.tbPersonasPer_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Per_UsuarioModifica);

                entity.HasOne(d => d.Per_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbPersonasPer_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Per_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbPersonasHistorial>(entity =>
            {
                entity.HasKey(e => e.Per_Id)
                    .HasName("PK__tbPerson__2705F940DE22EF91");

                entity.ToTable("tbPersonasHistorial", "bitacoras");

                entity.HasIndex(e => e.Per_Identidad, "UQ__tbPerson__0DB138838F2B992F")
                    .IsUnique();

                entity.HasIndex(e => e.Per_CorreoElectronico, "UQ__tbPerson__39641632A33285AB")
                    .IsUnique();

                entity.Property(e => e.Accion)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.EsActivo).HasDefaultValueSql("((1))");

                entity.Property(e => e.EsEliminado).HasDefaultValueSql("((0))");

                entity.Property(e => e.Fecha).HasColumnType("datetime");

                entity.Property(e => e.HostName)
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Per_ApellidoMaterno).HasMaxLength(50);

                entity.Property(e => e.Per_ApellidoPaterno).HasMaxLength(50);

                entity.Property(e => e.Per_CorreoElectronico)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Per_Direccion)
                    .HasMaxLength(150)
                    .IsUnicode(false);

                entity.Property(e => e.Per_FechaNacimiento).HasColumnType("date");

                entity.Property(e => e.Per_Identidad)
                    .HasMaxLength(13)
                    .IsUnicode(false);

                entity.Property(e => e.Per_PrimerNombre).HasMaxLength(50);

                entity.Property(e => e.Per_SegundoNombre).HasMaxLength(50);

                entity.Property(e => e.Per_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Per_Telefono)
                    .HasMaxLength(9)
                    .IsUnicode(false);

                entity.Property(e => e.Usuario)
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbRecibos>(entity =>
            {
                entity.HasKey(e => e.Rec_Id)
                    .HasName("PK__tbRecibo__81BCD9CA12E9E8C1");

                entity.ToTable("tbRecibos", "finanza");

                entity.HasIndex(e => e.Rec_NumeroRecibo, "UQ__tbRecibo__A5EDFF0DA45CF2DC")
                    .IsUnique();

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.Property(e => e.Rec_FechaEmision)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.Property(e => e.Rec_NumeroRecibo)
                    .IsRequired()
                    .HasMaxLength(40);

                entity.Property(e => e.Rec_RutaArchivo).HasMaxLength(260);

                entity.HasOne(d => d.Pag)
                    .WithMany(p => p.tbRecibos)
                    .HasForeignKey(d => d.Pag_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbRecibos_tbPagos");
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.Rol_Id);

                entity.ToTable("tbRoles", "seguridad");

                entity.Property(e => e.Rol_Id).HasComment("Identificador único del rol.");

                entity.Property(e => e.Rol_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasComment("Descripción del rol.");

                entity.Property(e => e.Rol_EsEliminado).HasComment("Indica si el rol ha sido eliminado (1) o no (0).");

                entity.Property(e => e.Rol_Estado).HasComment("Indica si el rol está activo (1) o no (0).");

                entity.Property(e => e.Rol_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del rol.");

                entity.Property(e => e.Rol_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del rol.");

                entity.Property(e => e.Rol_UsuarioModifica).HasComment("Identificador del usuario que modificó el rol.");

                entity.Property(e => e.Rol_UsuarioRegistra).HasComment("Identificador del usuario que registró el rol.");
            });

            modelBuilder.Entity<tbSecciones>(entity =>
            {
                entity.HasKey(e => e.Sec_Id)
                    .HasName("PK__tbSeccio__8AC3A65F2253D990");

                entity.ToTable("tbSecciones", "app");

                entity.HasComment("Registra la cantidad de secciones que puede haber en el centro estudiantil.");

                entity.Property(e => e.Sec_Id).HasComment("Identificador único de la sección.");

                entity.Property(e => e.Sec_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Nombre de la sección.");

                entity.Property(e => e.Sec_EsEliminado).HasComment("Indica si la sección ha sido eliminada (1) o no (0).");

                entity.Property(e => e.Sec_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación de la sección.");

                entity.Property(e => e.Sec_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro de la sección.");

                entity.Property(e => e.Sec_UsuarioModifica).HasComment("Identificador del usuario que modificó la sección.");

                entity.Property(e => e.Sec_UsuarioRegistra).HasComment("Identificador del usuario que registró la sección.");

                entity.HasOne(d => d.Sec_UsuarioModificaNavigation)
                    .WithMany(p => p.tbSeccionesSec_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Sec_UsuarioModifica);

                entity.HasOne(d => d.Sec_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbSeccionesSec_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Sec_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbSemestres>(entity =>
            {
                entity.HasKey(e => e.Sem_Id)
                    .HasName("PK__tbSemest__9CC78E8B85EC92BC");

                entity.ToTable("tbSemestres", "app");

                entity.HasComment("Periodo por año de la materia.");

                entity.Property(e => e.Sem_Id).HasComment("Identificador único de la tabla.");

                entity.Property(e => e.Sem_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("Información sobre cual es el semestre.");

                entity.Property(e => e.Sem_EsActivo).HasComment("Indica si el semestre está activo (1) o no (0).");

                entity.Property(e => e.Sem_EsEliminado).HasComment("Indica si el semestre ha sido eliminado (1) o no (0).");

                entity.Property(e => e.Sem_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del semestre.");

                entity.Property(e => e.Sem_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del semestre.");

                entity.Property(e => e.Sem_UsuarioModifica).HasComment("Identificador del usuario que modificó el semestre.");

                entity.Property(e => e.Sem_UsuarioRegistra).HasComment("Identificador del usuario que registró el semestre.");

                entity.HasOne(d => d.Sem_UsuarioModificaNavigation)
                    .WithMany(p => p.tbSemestresSem_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Sem_UsuarioModifica);

                entity.HasOne(d => d.Sem_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbSemestresSem_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Sem_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbTarifas>(entity =>
            {
                entity.HasKey(e => e.Tar_Id)
                    .HasName("PK__tbTarifa__C9DAA4D53DFBFD7B");

                entity.ToTable("tbTarifas", "finanza");

                entity.HasIndex(e => new { e.Cpa_Id, e.Tar_AnioVigencia }, "IX_tbTarifas_CpaAnio");

                entity.Property(e => e.Per_FechaModifica).HasPrecision(0);

                entity.Property(e => e.Per_FechaRegistra)
                    .HasPrecision(0)
                    .HasDefaultValueSql("(sysdatetime())");

                entity.Property(e => e.Tar_Monto).HasColumnType("decimal(18, 2)");

                entity.HasOne(d => d.Cpa)
                    .WithMany(p => p.tbTarifas)
                    .HasForeignKey(d => d.Cpa_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbTarifas_tbConceptosPago");
            });

            modelBuilder.Entity<tbTitulos>(entity =>
            {
                entity.HasKey(e => e.Tit_Id)
                    .HasName("PK__tbTitulo__D8C3A821A9B0006F");

                entity.ToTable("tbTitulos", "app");

                entity.HasComment("Información del título.");

                entity.Property(e => e.Tit_Id).HasComment("Identificador único del titulo.");

                entity.Property(e => e.Tit_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasDefaultValueSql("((1))")
                    .HasComment("Nombre que tiene el titulo.");

                entity.Property(e => e.Tit_EsEliminado).HasComment("Indica si el título ha sido eliminado (1) o no (0).");

                entity.Property(e => e.Tit_FechaModifica)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de modificación del título.");

                entity.Property(e => e.Tit_FechaRegistra)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de registro del título.");

                entity.Property(e => e.Tit_UsuarioModifica).HasComment("Identificador del usuario que modificó el título.");

                entity.Property(e => e.Tit_UsuarioRegistra).HasComment("Identificador del usuario que registró el título.");

                entity.HasOne(d => d.Tit_UsuarioModificaNavigation)
                    .WithMany(p => p.tbTitulosTit_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Tit_UsuarioModifica);

                entity.HasOne(d => d.Tit_UsuarioRegistraNavigation)
                    .WithMany(p => p.tbTitulosTit_UsuarioRegistraNavigation)
                    .HasForeignKey(d => d.Tit_UsuarioRegistra)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.Usu_Id);

                entity.ToTable("tbUsuarios", "seguridad");

                entity.Property(e => e.Usu_Id).HasComment("Identificador único del usuario.");

                entity.Property(e => e.Emp_Id).HasComment("Identificador del empleado asociado al usuario.");

                entity.Property(e => e.Rol_Id).HasComment("Identificador del rol del usuario.");

                entity.Property(e => e.Usu_Contraseña)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasComment("Contraseña del usuario (normalmente encriptada).");

                entity.Property(e => e.Usu_EsActivo).HasComment("Indica si el usuario está activo (1) o no (0).");

                entity.Property(e => e.Usu_EsEliminado)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Indica si el usuario ha sido eliminado (1) o no (0).");

                entity.Property(e => e.Usu_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de creación del usuario.");

                entity.Property(e => e.Usu_Ip)
                    .HasMaxLength(16)
                    .IsUnicode(false)
                    .HasComment("Dirección IP del usuario.");

                entity.Property(e => e.Usu_Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasComment("Nombre de usuario.");

                entity.Property(e => e.Usu_Suspendido)
                    .HasDefaultValueSql("((0))")
                    .HasComment("Indica si el usuario está suspendido (1) o no (0).");

                entity.Property(e => e.Usu_fechaModificacion)
                    .HasColumnType("datetime")
                    .HasComment("Fecha y hora de la última modificación del usuario.");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}