// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbCursosHistorial
    {
        public int Cur_Id { get; set; }
        public int? Cno_Id { get; set; }
        public int? Aul_Id { get; set; }
        public int? Sec_Id { get; set; }
        public int? Niv_Id { get; set; }
        public int? mda_Id { get; set; }
        public bool? EsActivo { get; set; }
        public bool? EsEliminado { get; set; }
        public string Accion { get; set; }
        public DateTime? Fecha { get; set; }
        public string Usuario { get; set; }
        public string HostName { get; set; }
    }
}