// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_ObtenerCargosPendientesResult
    {
        public int cuentaCobrarId { get; set; }
        public string conceptoPago { get; set; }
        [Column("montoOriginal", TypeName = "decimal(18,2)")]
        public decimal montoOriginal { get; set; }
        [Column("montoDescuento", TypeName = "decimal(18,2)")]
        public decimal montoDescuento { get; set; }
        [Column("montoMora", TypeName = "decimal(18,2)")]
        public decimal montoMora { get; set; }
        [Column("montoTotal", TypeName = "decimal(18,2)")]
        public decimal montoTotal { get; set; }
        public DateTime fechaVencimiento { get; set; }
        public string estadoPago { get; set; }
        public DateTime fechaCreacion { get; set; }
        public string observaciones { get; set; }
    }
}
