// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_ObtenerHistoricoPagosResult
    {
        public int Pag_Id { get; set; }
        public DateTime Pag_FechaPago { get; set; }
        [Column("Pag_MontoTotal", TypeName = "decimal(18,2)")]
        public decimal Pag_MontoTotal { get; set; }
        public string Fpa_Descripcion { get; set; }
        public string Pag_NumeroReferencia { get; set; }
        public string numeroRecibo { get; set; }
        public string Alumno { get; set; }
        public string Pag_Observaciones { get; set; }
    }
}
