// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_ObtenerResumenFinancieroResult
    {
        [Column("totalDeuda", TypeName = "decimal(18,2)")]
        public decimal totalDeuda { get; set; }
        [Column("totalPagado", TypeName = "decimal(18,2)")]
        public decimal totalPagado { get; set; }
        [Column("totalPendiente", TypeName = "decimal(18,2)")]
        public decimal totalPendiente { get; set; }
        [Column("totalMora", TypeName = "decimal(18,2)")]
        public decimal totalMora { get; set; }
    }
}
