// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCuentasCobrar_ListByAlumnoResult
    {
        public int CuentaCobrarId { get; set; }
        public int AlumnoId { get; set; }
        public int ConceptoPagoId { get; set; }
        public int? TarifaId { get; set; }
        [Column("MontoOriginal", TypeName = "decimal(18,2)")]
        public decimal MontoOriginal { get; set; }
        [Column("MontoDescuento", TypeName = "decimal(18,2)")]
        public decimal MontoDescuento { get; set; }
        [Column("MontoMora", TypeName = "decimal(18,2)")]
        public decimal MontoMora { get; set; }
        [Column("MontoTotal", TypeName = "decimal(18,2)")]
        public decimal MontoTotal { get; set; }
        [Column("MontoPendiente", TypeName = "decimal(18,2)")]
        public decimal MontoPendiente { get; set; }
        public DateTime FechaEmision { get; set; }
        public DateTime FechaVencimiento { get; set; }
        public int EstadoPagoId { get; set; }
        public byte? Mes { get; set; }
        public short? Anio { get; set; }
        public string Observaciones { get; set; }
        public string ConceptoDescripcion { get; set; }
        public string EstadoPagoDescripcion { get; set; }
        [Column("TotalPagado", TypeName = "decimal(19,2)")]
        public decimal? TotalPagado { get; set; }
        public bool EsEliminado { get; set; }
        public int UsuarioRegistraId { get; set; }
        public string NombreCompletoUsuarioRegistra { get; set; }
        public DateTime FechaRegistro { get; set; }
        public int? UsuarioModificaId { get; set; }
        public string NombreCompletoUsuarioModifica { get; set; }
        public DateTime? FechaModifica { get; set; }
    }
}
