// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCuentasCobrar_ListResult
    {
        [Column("# Fila")]
        public long? Fila { get; set; }
        public int Cco_Id { get; set; }
        public int Alu_Id { get; set; }
        public int Cpa_Id { get; set; }
        public int? Tar_Id { get; set; }
        [Column("Cco_MontoOriginal", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoOriginal { get; set; }
        [Column("Cco_MontoDescuento", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoDescuento { get; set; }
        [Column("Cco_MontoMora", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoMora { get; set; }
        [Column("Cco_MontoTotal", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoTotal { get; set; }
        [Column("Cco_MontoPendiente", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoPendiente { get; set; }
        public DateTime Cco_FechaEmision { get; set; }
        public DateTime Cco_FechaVencimiento { get; set; }
        public int Epa_Id { get; set; }
        public string Cpa_Descripcion { get; set; }
        public string Epa_Descripcion { get; set; }
    }
}
