// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbDescuentosAplicados_DetailResult
    {
        public int Dap_Id { get; set; }
        public int Cco_Id { get; set; }
        public int Des_Id { get; set; }
        [Column("Dap_MontoAplicado", TypeName = "decimal(18,2)")]
        public decimal Dap_MontoAplicado { get; set; }
        public string Dap_Justificacion { get; set; }
        public string Des_Descripcion { get; set; }
        public string Des_TipoDescuento { get; set; }
        [Column("Des_Valor", TypeName = "decimal(18,2)")]
        public decimal Des_Valor { get; set; }
        [Column("Cco_MontoOriginal", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoOriginal { get; set; }
        [Column("Cco_MontoTotal", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoTotal { get; set; }
        public bool Dap_EsEliminado { get; set; }
        public int Dap_UsuarioRegistra { get; set; }
        public string NombreCompletoUsuarioRegistra { get; set; }
        public DateTime Dap_FechaRegistra { get; set; }
        public int? Dap_UsuarioModifica { get; set; }
        public string NombreCompletoUsuarioModifica { get; set; }
        public DateTime? Dap_FechaModifica { get; set; }
    }
}
