// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCuentasCobrar_ListResult
    {
        [Column("Cco_MontoOriginal", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoOriginal { get; set; }
        [Column("Cco_MontoDescuento", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoDescuento { get; set; }
        [Column("Cco_MontoMora", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoMora { get; set; }
        [Column("Cco_MontoTotal", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoTotal { get; set; }
        [Column("Cco_MontoPendiente", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoPendiente { get; set; }
        public DateTime Cco_FechaEmision { get; set; }
        public DateTime Cco_FechaVencimiento { get; set; }
        public string Cco_Observaciones { get; set; }
        public string DescripcionConceptoPago { get; set; }
        public string DescripcionEstadoPago { get; set; }
        public string NombreCompletoAlumno { get; set; }
    }
}
