// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbConceptosPago_ListResult
    {
        public string Cpa_Descripcion { get; set; }
        public bool Cpa_EsRecurrente { get; set; }
        public bool Cpa_EsObligatorio { get; set; }
        public bool Cpa_EsActivo { get; set; }
    }
}
