// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbPagos_ListResult
    {
        [Column("Pag_MontoTotal", TypeName = "decimal(18,2)")]
        public decimal Pag_MontoTotal { get; set; }
        public DateTime Pag_FechaPago { get; set; }
        public string Pag_NumeroReferencia { get; set; }
        public string Pag_Observaciones { get; set; }
        public string NombreCompletoAlumno { get; set; }
        public string DescripcionFormaPago { get; set; }
        public string NombreCompletoEncargado { get; set; }
        public string NombreUsuarioRegistraPago { get; set; }
    }
}
