// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbPagos_ListResult
    {
        public long? Fila { get; set; }
        public int Pag_Id { get; set; }
        public DateTime Pag_FechaPago { get; set; }
        [Column("Pag_MontoTotal", TypeName = "decimal(18,2)")]
        public decimal Pag_MontoTotal { get; set; }
        public string Pag_NumeroReferencia { get; set; }
        public string Pag_Observaciones { get; set; }
        public string FormaPago { get; set; }
        public string Alumno { get; set; }
        public string Encargado { get; set; }
        public string Usuario { get; set; }
        public string Rec_NumeroRecibo { get; set; }
        public DateTime? Rec_FechaEmision { get; set; }
    }
}
