// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCuentasCobrar_ListResult
    {
        public long? Fila { get; set; }
        public int Cco_Id { get; set; }
        public string Concepto { get; set; }
        public string Alumno { get; set; }
        [Column("Pendiente", TypeName = "decimal(18,2)")]
        public decimal Pendiente { get; set; }
        public DateTime FechaVence { get; set; }
        public string EstadoPago { get; set; }
    }
}
