// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbFormasPago_ListResult
    {
        [Column("# Fila")]
        public long? Fila { get; set; }
        public int Fpa_Id { get; set; }
        public string Fpa_Descripcion { get; set; }
        public bool Fpa_EsActivo { get; set; }
    }
}
