// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbConceptosPago_DetailResult
    {
        public int Cpa_Id { get; set; }
        public string Cpa_Descripcion { get; set; }
        public bool Cpa_EsRecurrente { get; set; }
        public bool Cpa_EsObligatorio { get; set; }
        public bool Cpa_EsActivo { get; set; }
        public bool Per_EsEliminado { get; set; }
        public int Per_UsuarioRegistra { get; set; }
        public string NombreCompletoUsuarioRegistra { get; set; }
        public DateTime Per_FechaRegistra { get; set; }
        public int? Per_UsuarioModifica { get; set; }
        public string NombreCompletoUsuarioModifica { get; set; }
        public DateTime? Per_FechaModifica { get; set; }
    }
}
