// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbConceptosPago_InsertResult
    {
        [Column("NewId", TypeName = "decimal(38,0)")]
        public decimal? NewId { get; set; }
    }
}
