// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbDescuentosAplicados_FindResult
    {
        public int Dap_Id { get; set; }
        public int Cco_Id { get; set; }
        public int Des_Id { get; set; }
        [Column("Dap_MontoAplicado", TypeName = "decimal(18,2)")]
        public decimal Dap_MontoAplicado { get; set; }
        public string DescripcionDescuento { get; set; }
        public string NombreCompletoAlumno { get; set; }
    }
}
