// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbEstadosPago_ExistResult
    {
        public bool? Exists { get; set; }
        public string Message { get; set; }
    }
}
