// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbMoratorias_FindResult
    {
        public int Mor_Id { get; set; }
        public int Cco_Id { get; set; }
        public int Mor_DiasAtraso { get; set; }
        [Column("Mor_Porcentaje", TypeName = "decimal(9,4)")]
        public decimal Mor_Porcentaje { get; set; }
        [Column("Mor_MontoMora", TypeName = "decimal(18,2)")]
        public decimal Mor_MontoMora { get; set; }
        public DateTime Mor_FechaCalculo { get; set; }
        public bool Mor_EsEliminado { get; set; }
        public int Mor_UsuarioRegistra { get; set; }
        public DateTime Mor_FechaRegistra { get; set; }
        public int? Mor_UsuarioModifica { get; set; }
        public DateTime? Mor_FechaModifica { get; set; }
    }
}
