// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbPagosDetalle_ListResult
    {
        public long? Fila { get; set; }
        public int Pde_Id { get; set; }
        public int Pag_Id { get; set; }
        public int Cco_Id { get; set; }
        [Column("Pde_MontoAplicado", TypeName = "decimal(18,2)")]
        public decimal Pde_MontoAplicado { get; set; }
        public bool Pde_EsEliminado { get; set; }
        public int Pde_UsuarioRegistra { get; set; }
        public DateTime Pde_FechaRegistra { get; set; }
        public int? Pde_UsuarioModifica { get; set; }
        public DateTime? Pde_FechaModifica { get; set; }
    }
}
