// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbPagos_FindResult
    {
        public int Pag_Id { get; set; }
        public int Alu_Id { get; set; }
        public int? Enc_Id { get; set; }
        public int Fpa_Id { get; set; }
        [Column("Pag_MontoTotal", TypeName = "decimal(18,2)")]
        public decimal Pag_MontoTotal { get; set; }
        public DateTime Pag_FechaPago { get; set; }
        public string Pag_NumeroReferencia { get; set; }
        public string Pag_Observaciones { get; set; }
        public int Usu_Id { get; set; }
        public bool Pag_EsEliminado { get; set; }
        public int Pag_UsuarioRegistra { get; set; }
        public DateTime Pag_FechaRegistra { get; set; }
        public int? Pag_UsuarioModifica { get; set; }
        public DateTime? Pag_FechaModifica { get; set; }
    }
}
