// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbRecibos_ListResult
    {
        public string Rec_NumeroRecibo { get; set; }
        public DateTime Rec_FechaEmision { get; set; }
        public string Rec_RutaArchivo { get; set; }
        public string NombreCompletoAlumno { get; set; }
    }
}
