// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbEstadosPago_DetailResult
    {
        public int Epa_Id { get; set; }
        public string Epa_Descripcion { get; set; }
        public bool Epa_EsActivo { get; set; }
        public int? CantidadCuentas { get; set; }
        public bool Epa_EsEliminado { get; set; }
        public int Epa_UsuarioRegistra { get; set; }
        public string NombreCompletoUsuarioRegistra { get; set; }
        public DateTime Epa_FechaRegistra { get; set; }
        public int? Epa_UsuarioModifica { get; set; }
        public string NombreCompletoUsuarioModifica { get; set; }
        public DateTime? Epa_FechaModifica { get; set; }
    }
}
