// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbPagosDetalle_ListResult
    {
        [Column("Pde_MontoAplicado", TypeName = "decimal(18,2)")]
        public decimal Pde_MontoAplicado { get; set; }
        public string NombreCompletoAlumno { get; set; }
        public string DescripcionConceptoPago { get; set; }
    }
}
