// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbFormasPago_DetailResult
    {
        public int Fpa_Id { get; set; }
        public string Fpa_Descripcion { get; set; }
        public bool Fpa_EsActivo { get; set; }
        public int? CantidadPagos { get; set; }
        public bool Fpa_EsEliminado { get; set; }
        public int Fpa_UsuarioRegistra { get; set; }
        public string NombreCompletoUsuarioRegistra { get; set; }
        public DateTime Fpa_FechaRegistra { get; set; }
        public int? Fpa_UsuarioModifica { get; set; }
        public string NombreCompletoUsuarioModifica { get; set; }
        public DateTime? Fpa_FechaModifica { get; set; }
    }
}
