// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbMoratorias_ListResult
    {
        public long? Fila { get; set; }
        public int Mor_Id { get; set; }
        public int Cco_Id { get; set; }
        public int Mor_DiasAtraso { get; set; }
        [Column("Mor_Porcentaje", TypeName = "decimal(9,4)")]
        public decimal Mor_Porcentaje { get; set; }
        [Column("Mor_MontoMora", TypeName = "decimal(18,2)")]
        public decimal Mor_MontoMora { get; set; }
        public DateTime Mor_FechaCalculo { get; set; }
        [Column("Cco_MontoOriginal", TypeName = "decimal(18,2)")]
        public decimal Cco_MontoOriginal { get; set; }
        public DateTime Cco_FechaVencimiento { get; set; }
    }
}
