// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbDescuentos_DetailResult
    {
        public int Des_Id { get; set; }
        public string Des_Descripcion { get; set; }
        public string Des_TipoDescuento { get; set; }
        [Column("Des_Valor", TypeName = "decimal(18,2)")]
        public decimal Des_Valor { get; set; }
        public bool Des_EsActivo { get; set; }
        public bool Per_EsEliminado { get; set; }
        public int Per_UsuarioRegistra { get; set; }
        public string NombreCompletoUsuarioRegistra { get; set; }
        public DateTime Per_FechaRegistra { get; set; }
        public int? Per_UsuarioModifica { get; set; }
        public string NombreCompletoUsuarioModifica { get; set; }
        public DateTime? Per_FechaModifica { get; set; }
    }
}
