// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbConceptosPago
    {
        public tbConceptosPago()
        {
            tbCuentasCobrar = new HashSet<tbCuentasCobrar>();
            tbTarifas = new HashSet<tbTarifas>();
        }

        public int Cpa_Id { get; set; }
        public string Cpa_Descripcion { get; set; }
        public bool Cpa_EsRecurrente { get; set; }
        public bool Cpa_EsObligatorio { get; set; }
        public bool Cpa_EsActivo { get; set; }
        public bool Cpa_EsEliminado { get; set; }
        public int Cpa_UsuarioRegistra { get; set; }
        public DateTime Cpa_FechaRegistra { get; set; }
        public int? Cpa_UsuarioModifica { get; set; }
        public DateTime? Cpa_FechaModifica { get; set; }

        public virtual ICollection<tbCuentasCobrar> tbCuentasCobrar { get; set; }
        public virtual ICollection<tbTarifas> tbTarifas { get; set; }
    }
}