// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbCuentasCobrar
    {
        public tbCuentasCobrar()
        {
            tbDescuentosAplicados = new HashSet<tbDescuentosAplicados>();
            tbMoratorias = new HashSet<tbMoratorias>();
            tbPagosDetalle = new HashSet<tbPagosDetalle>();
        }

        public int Cco_Id { get; set; }
        public int Alu_Id { get; set; }
        public int Cpa_Id { get; set; }
        public int? Tar_Id { get; set; }
        public decimal Cco_MontoOriginal { get; set; }
        public decimal Cco_MontoDescuento { get; set; }
        public decimal Cco_MontoMora { get; set; }
        public decimal Cco_MontoTotal { get; set; }
        public decimal Cco_MontoPendiente { get; set; }
        public DateTime Cco_FechaEmision { get; set; }
        public DateTime Cco_FechaVencimiento { get; set; }
        public int Epa_Id { get; set; }
        public string Cco_Observaciones { get; set; }
        public bool Per_EsEliminado { get; set; }
        public int Per_UsuarioRegistra { get; set; }
        public DateTime Per_FechaRegistra { get; set; }
        public int? Per_UsuarioModifica { get; set; }
        public DateTime? Per_FechaModifica { get; set; }

        public virtual tbConceptosPago Cpa { get; set; }
        public virtual tbEstadosPago Epa { get; set; }
        public virtual tbTarifas Tar { get; set; }
        public virtual ICollection<tbDescuentosAplicados> tbDescuentosAplicados { get; set; }
        public virtual ICollection<tbMoratorias> tbMoratorias { get; set; }
        public virtual ICollection<tbPagosDetalle> tbPagosDetalle { get; set; }
    }
}