// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbCuentasCobrarHistorial
    {
        public int Cgh_Id { get; set; }
        public int Cco_Id { get; set; }
        public string Cgh_Accion { get; set; }
        public string Cgh_Detalle { get; set; }
        public DateTime Cgh_Fecha { get; set; }
        public int Cgh_Usuario { get; set; }
    }
}