// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbDescuentosAplicados
    {
        public int Dap_Id { get; set; }
        public int Cco_Id { get; set; }
        public int Des_Id { get; set; }
        public decimal Dap_MontoAplicado { get; set; }
        public string Dap_Justificacion { get; set; }
        public bool Dap_EsEliminado { get; set; }
        public int Dap_UsuarioRegistra { get; set; }
        public DateTime Dap_FechaRegistra { get; set; }
        public int? Dap_UsuarioModifica { get; set; }
        public DateTime? Dap_FechaModifica { get; set; }

        public virtual tbCuentasCobrar Cco { get; set; }
        public virtual tbDescuentos Des { get; set; }
    }
}