// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbDescuentos
    {
        public tbDescuentos()
        {
            tbDescuentosAplicados = new HashSet<tbDescuentosAplicados>();
        }

        public int Des_Id { get; set; }
        public string Des_Descripcion { get; set; }
        public string Des_TipoDescuento { get; set; }
        public decimal Des_Valor { get; set; }
        public bool Des_EsActivo { get; set; }
        public bool Per_EsEliminado { get; set; }
        public int Per_UsuarioRegistra { get; set; }
        public DateTime Per_FechaRegistra { get; set; }
        public int? Per_UsuarioModifica { get; set; }
        public DateTime? Per_FechaModifica { get; set; }

        public virtual ICollection<tbDescuentosAplicados> tbDescuentosAplicados { get; set; }
    }
}