// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbFormasPago
    {
        public tbFormasPago()
        {
            tbPagos = new HashSet<tbPagos>();
        }

        public int Fpa_Id { get; set; }
        public string Fpa_Descripcion { get; set; }
        public bool Fpa_EsActivo { get; set; }
        public bool Per_EsEliminado { get; set; }
        public int Per_UsuarioRegistra { get; set; }
        public DateTime Per_FechaRegistra { get; set; }
        public int? Per_UsuarioModifica { get; set; }
        public DateTime? Per_FechaModifica { get; set; }

        public virtual ICollection<tbPagos> tbPagos { get; set; }
    }
}