// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbMoratorias
    {
        public int Mor_Id { get; set; }
        public int Cco_Id { get; set; }
        public int Mor_DiasAtraso { get; set; }
        public decimal Mor_Porcentaje { get; set; }
        public decimal Mor_MontoMora { get; set; }
        public DateTime Mor_FechaCalculo { get; set; }
        public bool Mor_EsEliminado { get; set; }
        public int Mor_UsuarioRegistra { get; set; }
        public DateTime Mor_FechaRegistra { get; set; }
        public int? Mor_UsuarioModifica { get; set; }
        public DateTime? Mor_FechaModifica { get; set; }

        public virtual tbCuentasCobrar Cco { get; set; }
    }
}