// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbPagos
    {
        public tbPagos()
        {
            tbPagosDetalle = new HashSet<tbPagosDetalle>();
            tbRecibos = new HashSet<tbRecibos>();
        }

        public int Pag_Id { get; set; }
        public int Alu_Id { get; set; }
        public int? Enc_Id { get; set; }
        public int Fpa_Id { get; set; }
        public decimal Pag_MontoTotal { get; set; }
        public DateTime Pag_FechaPago { get; set; }
        public string Pag_NumeroReferencia { get; set; }
        public string Pag_Observaciones { get; set; }
        public int Usu_Id { get; set; }
        public bool Pag_EsEliminado { get; set; }
        public int Pag_UsuarioRegistra { get; set; }
        public DateTime Pag_FechaRegistra { get; set; }
        public int? Pag_UsuarioModifica { get; set; }
        public DateTime? Pag_FechaModifica { get; set; }

        public virtual tbFormasPago Fpa { get; set; }
        public virtual ICollection<tbPagosDetalle> tbPagosDetalle { get; set; }
        public virtual ICollection<tbRecibos> tbRecibos { get; set; }
    }
}