// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbPagosDetalle
    {
        public int Pde_Id { get; set; }
        public int Pag_Id { get; set; }
        public int Cco_Id { get; set; }
        public decimal Pde_MontoAplicado { get; set; }
        public bool Pde_EsEliminado { get; set; }
        public int Pde_UsuarioRegistra { get; set; }
        public DateTime Pde_FechaRegistra { get; set; }
        public int? Pde_UsuarioModifica { get; set; }
        public DateTime? Pde_FechaModifica { get; set; }

        public virtual tbCuentasCobrar Cco { get; set; }
        public virtual tbPagos Pag { get; set; }
    }
}