// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbPagosHistorial
    {
        public int Pgh_Id { get; set; }
        public int Pag_Id { get; set; }
        public string Pgh_Accion { get; set; }
        public string Pgh_Detalle { get; set; }
        public DateTime Pgh_Fecha { get; set; }
        public int Pgh_Usuario { get; set; }
    }
}