// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbRecibos
    {
        public int Rec_Id { get; set; }
        public int Pag_Id { get; set; }
        public string Rec_NumeroRecibo { get; set; }
        public DateTime Rec_FechaEmision { get; set; }
        public string Rec_RutaArchivo { get; set; }
        public bool Rec_EsEliminado { get; set; }
        public int Rec_UsuarioRegistra { get; set; }
        public DateTime Rec_FechaRegistra { get; set; }
        public int? Rec_UsuarioModifica { get; set; }
        public DateTime? Rec_FechaModifica { get; set; }

        public virtual tbPagos Pag { get; set; }
    }
}