// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbTarifas
    {
        public tbTarifas()
        {
            tbCuentasCobrar = new HashSet<tbCuentasCobrar>();
        }

        public int Tar_Id { get; set; }
        public int Cpa_Id { get; set; }
        public int? Niv_Id { get; set; }
        public int? Cun_Id { get; set; }
        public decimal Tar_Monto { get; set; }
        public short Tar_AnioVigencia { get; set; }
        public bool Tar_EsEliminado { get; set; }
        public int Tar_UsuarioRegistra { get; set; }
        public DateTime Tar_FechaRegistra { get; set; }
        public int? Tar_UsuarioModifica { get; set; }
        public DateTime? Tar_FechaModifica { get; set; }
        public bool Tar_EsActivo { get; set; }

        public virtual tbConceptosPago Cpa { get; set; }
        public virtual ICollection<tbCuentasCobrar> tbCuentasCobrar { get; set; }
    }
}