// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbAlumnos
    {
        public tbAlumnos()
        {
            tbEncargados_tbAlumnos = new HashSet<tbEncargados_tbAlumnos>();
        }

        /// <summary>
        /// Identificador del alumno
        /// </summary>
        public int Alu_Id { get; set; }
        /// <summary>
        /// Indica el identificador único de la persona.
        /// </summary>
        public int Per_Id { get; set; }
        public int? Niv_Id { get; set; }
        public int? Cun_Id { get; set; }
        public int? Mda_Id { get; set; }
        /// <summary>
        /// Indica el identificador único del curso.
        /// </summary>
        public int Cur_Id { get; set; }
        public int? Sec_Id { get; set; }
        /// <summary>
        /// Indica el identificador único del estado.
        /// </summary>
        public int Est_Id { get; set; }

        public virtual tbCursosNiveles Cun { get; set; }
        public virtual tbCursos Cur { get; set; }
        public virtual tbEstados Est { get; set; }
        public virtual tbModalidades Mda { get; set; }
        public virtual tbNivelesEducativos Niv { get; set; }
        public virtual tbPersonas Per { get; set; }
        public virtual tbSecciones Sec { get; set; }
        public virtual ICollection<tbEncargados_tbAlumnos> tbEncargados_tbAlumnos { get; set; }
    }
}
