// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Registra los puestos que puede tener un empleado en el colegio.
    /// </summary>
    public partial class tbCargos
    {
        public tbCargos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        /// <summary>
        /// Identificador único del puesto.
        /// </summary>
        public int Car_Id { get; set; }
        /// <summary>
        /// Dato informativo del cargo.
        /// </summary>
        public string Car_Descripcion { get; set; }
        /// <summary>
        /// Indica si el cargo ha sido eliminado (1) o no (0).
        /// 
        /// </summary>
        public bool Car_EsEliminado { get; set; }
        /// <summary>
        /// Identificador del usuario que registró el cargo.
        /// 
        /// </summary>
        public int Car_UsuarioRegistra { get; set; }
        /// <summary>
        /// Fecha y hora de registro del cargo.
        /// 
        /// </summary>
        public DateTime Car_FechaRegistra { get; set; }
        /// <summary>
        /// Identificador del usuario que modificó el cargo.
        /// 
        /// </summary>
        public int? Car_UsuarioModifica { get; set; }
        /// <summary>
        /// Fecha y hora de modificación del cargo.
        /// </summary>
        public DateTime? Car_FechaModifica { get; set; }

        public virtual tbUsuarios Car_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Car_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}