// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbCursosNiveles
    {
        public tbCursosNiveles()
        {
            tbAlumnos = new HashSet<tbAlumnos>();
            tbCursos_tbCursosNiveles = new HashSet<tbCursos_tbCursosNiveles>();
            tbHorarioAlumnos = new HashSet<tbHorarioAlumnos>();
            tbHorarioProfesores = new HashSet<tbHorarioProfesores>();
            tbModalidades_tbCursosNiveles = new HashSet<tbModalidades_tbCursosNiveles>();
        }

        public int Cun_Id { get; set; }
        public string Cun_Descripcion { get; set; }
        public int Niv_Id { get; set; }
        public bool Cun_EsEliminado { get; set; }
        public int Cun_UsuarioRegistra { get; set; }
        public DateTime Cun_FechaRegistra { get; set; }
        public int? Cun_UsuarioModifica { get; set; }
        public DateTime? Cun_FechaModifica { get; set; }

        public virtual tbNivelesEducativos Niv { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        public virtual ICollection<tbCursos_tbCursosNiveles> tbCursos_tbCursosNiveles { get; set; }
        public virtual ICollection<tbHorarioAlumnos> tbHorarioAlumnos { get; set; }
        public virtual ICollection<tbHorarioProfesores> tbHorarioProfesores { get; set; }
        public virtual ICollection<tbModalidades_tbCursosNiveles> tbModalidades_tbCursosNiveles { get; set; }
    }
}
