// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbCursos_tbSecciones
    {
        public int Cur_Id { get; set; }
        public int Sec_Id { get; set; }
        public int Aul_Id { get; set; }

        public virtual tbAulas Aul { get; set; }
        public virtual tbCursos Cur { get; set; }
        public virtual tbSecciones Sec { get; set; }
    }
}
