// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbCursos_tbCursosNiveles
    {
        public int Cur_Id { get; set; }
        public int Cun_Id { get; set; }

        public virtual tbCursosNiveles Cun { get; set; }
        public virtual tbCursos Cur { get; set; }
    }
}
