// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.seguridad;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbCursosNombres
    {
        public string Cno_Id { get; set; }
        public string Cno_Descripcion { get; set; }
        public int Niv_Id { get; set; }
        public bool Cno_EsEliminado { get; set; }
        public int Cno_UsuarioRegistra { get; set; }
        public DateTime Cno_FechaRegistra { get; set; }
        public int? Cno_UsuarioModifica { get; set; }
        public DateTime? Cno_FechaModifica { get; set; }

        public virtual tbUsuarios Cno_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Cno_UsuarioRegistraNavigation { get; set; }
    }
}
