// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Administra la información de los cursos.
    /// </summary>
    public partial class tbCursos
    {
        public tbCursos()
        {
            tbAlumnos = new HashSet<tbAlumnos>();
            tbCursos_tbSecciones = new HashSet<tbCursos_tbSecciones>();
            tbHorarioProfesores = new HashSet<tbHorarioProfesores>();
            Cun = new HashSet<tbCursosNiveles>();
            Mat = new HashSet<tbMaterias>();
            Mda = new HashSet<tbModalidades>();
        }

        /// <summary>
        /// Identificador único del registro en la tabla.
        /// </summary>
        public int Cur_Id { get; set; }
        /// <summary>
        /// Identificador de un nombre en el curso.
        /// </summary>
        public string Cur_Nombre { get; set; }
        /// <summary>
        /// Identificador unico de la tabla tbNivelesEducativos.
        /// </summary>
        public int Niv_Id { get; set; }
        /// <summary>
        /// Estado en el que se encuentra el curso.
        /// </summary>
        public bool Cur_EsActivo { get; set; }
        public bool Cur_EsEliminado { get; set; }
        public int Cur_UsuarioRegistra { get; set; }
        public DateTime Cur_FechaRegistra { get; set; }
        public int? Cur_UsuarioModifica { get; set; }
        public DateTime? Cur_FechaModifica { get; set; }

        public virtual tbUsuarios Cur_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Cur_UsuarioRegistraNavigation { get; set; }
        public virtual tbNivelesEducativos Niv { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        public virtual ICollection<tbCursos_tbSecciones> tbCursos_tbSecciones { get; set; }
        public virtual ICollection<tbHorarioProfesores> tbHorarioProfesores { get; set; }

        public virtual ICollection<tbCursosNiveles> Cun { get; set; }
        public virtual ICollection<tbMaterias> Mat { get; set; }
        public virtual ICollection<tbModalidades> Mda { get; set; }
    }
}