// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;
using Gestion.Colegial.Entities.Entities.seguridad;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbCursos
    {
        public tbCursos()
        {
            tbAlumnos = new HashSet<tbAlumnos>();
            tbCursos_tbCursosNiveles = new HashSet<tbCursos_tbCursosNiveles>();
            tbCursos_tbMaterias = new HashSet<tbCursos_tbMaterias>();
            tbCursos_tbModalidades = new HashSet<tbCursos_tbModalidades>();
            tbCursos_tbSecciones = new HashSet<tbCursos_tbSecciones>();
            tbHorarioProfesores = new HashSet<tbHorarioProfesores>();
        }

        /// <summary>
        /// Identificador único del registro en la tabla.
        /// </summary>
        public int Cur_Id { get; set; }
        /// <summary>
        /// Identificador de un nombre en el curso.
        /// </summary>
        public string Cur_Nombre { get; set; }
        /// <summary>
        /// Identificador del nivel del curso.
        /// </summary>
        public int Niv_Id { get; set; }
        public bool? Cur_EsActivo { get; set; }
        public bool Cur_EsEliminado { get; set; }
        public int Cur_UsuarioRegistra { get; set; }
        public DateTime Cur_FechaRegistra { get; set; }
        public int? Cur_UsuarioModifica { get; set; }
        public DateTime? Cur_FechaModifica { get; set; }
        //Array de enteros para los id de los checkbox
        public int[] Modalidades { get; set; }
        public int[] CursoNiveles { get; set; }
        public int[] Secciones { get; set; }
        public int[] Materias { get; set; }

        public virtual tbUsuarios Cur_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Cur_UsuarioRegistraNavigation { get; set; }
        public virtual tbNivelesEducativos Niv { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        public virtual ICollection<tbCursos_tbCursosNiveles> tbCursos_tbCursosNiveles { get; set; }
        public virtual ICollection<tbCursos_tbMaterias> tbCursos_tbMaterias { get; set; }
        public virtual ICollection<tbCursos_tbModalidades> tbCursos_tbModalidades { get; set; }
        public virtual ICollection<tbCursos_tbSecciones> tbCursos_tbSecciones { get; set; }
        public virtual ICollection<tbHorarioProfesores> tbHorarioProfesores { get; set; }
    }
}
