// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbDepartamentoEmpleados
    {
        public tbDepartamentoEmpleados()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int Dep_Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}