// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;
using Gestion.Colegial.Entities.Entities.seguridad;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbDias
    {
        public tbDias()
        {
            tbHorarioAlumnos = new HashSet<tbHorarioAlumnos>();
            tbHorarioProfesores = new HashSet<tbHorarioProfesores>();
        }

        /// <summary>
        /// Identificador único de los dias.
        /// </summary>
        public int Dia_Id { get; set; }
        /// <summary>
        /// Nombre del dia.
        /// </summary>
        public string Dia_Descripcion { get; set; }
        public bool Dia_EsEliminado { get; set; }
        public int Dia_UsuarioRegistra { get; set; }
        public DateTime Dia_FechaRegistra { get; set; }
        public int? Dia_UsuarioModifica { get; set; }
        public DateTime? Dia_FechaModifica { get; set; }

        public virtual tbUsuarios Dia_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Dia_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbHorarioAlumnos> tbHorarioAlumnos { get; set; }
        public virtual ICollection<tbHorarioProfesores> tbHorarioProfesores { get; set; }
    }
}
