// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;
using Gestion.Colegial.Entities.Entities.seguridad;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbDuraciones
    {
        public tbDuraciones()
        {
            tbMaterias = new HashSet<tbMaterias>();
        }

        /// <summary>
        /// Identificador único de la duracion.
        /// </summary>
        public int Dur_Id { get; set; }
        /// <summary>
        /// Información del tiempo designado para una materia.
        /// </summary>
        public string Dur_Descripcion { get; set; }
        public bool Dur_EsEliminado { get; set; }
        public int Dur_UsuarioRegistra { get; set; }
        public DateTime Dur_FechaRegistra { get; set; }
        public int? Dur_UsuarioModifica { get; set; }
        public DateTime? Dur_FechaModifica { get; set; }

        public virtual tbUsuarios Dur_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Dur_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbMaterias> tbMaterias { get; set; }
    }
}
