// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbEmpleados_tbMaterias
    {
        public int Emp_Id { get; set; }
        public int Mat_Id { get; set; }

        public virtual tbEmpleados Emp { get; set; }
        public virtual tbMaterias Mat { get; set; }
    }
}
