// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbEmpleados_tbMaterias = new HashSet<tbEmpleados_tbMaterias>();
        }

        public int Emp_Id { get; set; }
        public string Emp_Codigo { get; set; }
        public int Per_Id { get; set; }
        public int Tit_Id { get; set; }
        public int Car_Id { get; set; }

        public virtual tbCargos Car { get; set; }
        public virtual tbPersonas Per { get; set; }
        public virtual tbTitulos Tit { get; set; }
        public virtual ICollection<tbEmpleados_tbMaterias> tbEmpleados_tbMaterias { get; set; }
    }
}
