// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene los encargados relacionados con el alumno.
    /// </summary>
    public partial class tbEncargados_tbAlumnos
    {
        /// <summary>
        /// Identificador único del encargado.
        /// </summary>
        public int Enc_Id { get; set; }
        /// <summary>
        /// Identificador único del alumno.
        /// </summary>
        public int Alu_Id { get; set; }
        /// <summary>
        /// Identificador único del parcial.
        /// </summary>
        public int Par_Id { get; set; }

        public virtual tbAlumnos Alu { get; set; }
        public virtual tbEncargados Enc { get; set; }
        public virtual tbParentescos Par { get; set; }
    }
}