// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbEventos
    {
        /// <summary>
        /// Identificador unico de la tabla tbEventos.
        /// </summary>
        public int even_Id { get; set; }
        /// <summary>
        /// Nombre del evento a realizarse.
        /// </summary>
        public string even_Nombre { get; set; }
        /// <summary>
        /// Información adicional o informativa que resume sobre lo que trata el evento.
        /// </summary>
        public string even_Informacion { get; set; }
        /// <summary>
        /// Fecha indicada para realizacion del evento.
        /// </summary>
        public DateTime even_Fecha { get; set; }
        /// <summary>
        /// Hora exacta en el que se efectuara el evento.
        /// </summary>
        public TimeSpan even_Hora { get; set; }
        /// <summary>
        /// En este campo se indica si el registro se elimino completamente.
        /// </summary>
        public bool even_Concluido { get; set; }
        /// <summary>
        /// En este campo se indica si el registro se elimino completamente.
        /// </summary>
        public bool even_EsEliminado { get; set; }
        /// <summary>
        /// ID del usuario que realiza la acción.
        /// </summary>
        public int even_UsuarioRegistra { get; set; }
        /// <summary>
        /// Fecha que se realizo la acción de ingresar.
        /// </summary>
        public DateTime even_FechaRegistra { get; set; }
        /// <summary>
        /// ID del usuario que realiza la acción.
        /// </summary>
        public int? even_UsuarioModifica { get; set; }
        /// <summary>
        /// Fecha que se realizo la acción de modificar.
        /// </summary>
        public DateTime? even_FechaModifica { get; set; }
    }
}
