// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Administra las horas de labor diaria.
    /// </summary>
    public partial class tbHoras
    {
        public tbHoras()
        {
            tbHorarioAlumnosHoAl_HoraFinalizaNavigation = new HashSet<tbHorarioAlumnos>();
            tbHorarioAlumnosHoAl_HoraInicioNavigation = new HashSet<tbHorarioAlumnos>();
            tbHorarioProfesoresHoPr_HoraFinalizaNavigation = new HashSet<tbHorarioProfesores>();
            tbHorarioProfesoresHoPr_HoraInicioNavigation = new HashSet<tbHorarioProfesores>();
        }

        /// <summary>
        /// Identificador único de la hora.
        /// </summary>
        public int Hor_Id { get; set; }
        /// <summary>
        /// Descripción de la hora indicada.
        /// </summary>
        public string Hor_Hora { get; set; }
        /// <summary>
        /// Indica si la hora ha sido eliminada (1) o no (0).
        /// </summary>
        public bool Hor_EsEliminado { get; set; }
        /// <summary>
        /// Identificador del usuario que registró la hora.
        /// </summary>
        public int Hor_UsuarioRegistra { get; set; }
        /// <summary>
        /// Fecha y hora de registro de la hora.
        /// </summary>
        public DateTime Hor_FechaRegistra { get; set; }
        /// <summary>
        /// Identificador del usuario que modificó la hora.
        /// </summary>
        public int? Hor_UsuarioModifica { get; set; }
        /// <summary>
        /// Fecha y hora de modificación de la hora.
        /// </summary>
        public DateTime? Hor_FechaModifica { get; set; }

        public virtual ICollection<tbHorarioAlumnos> tbHorarioAlumnosHoAl_HoraFinalizaNavigation { get; set; }
        public virtual ICollection<tbHorarioAlumnos> tbHorarioAlumnosHoAl_HoraInicioNavigation { get; set; }
        public virtual ICollection<tbHorarioProfesores> tbHorarioProfesoresHoPr_HoraFinalizaNavigation { get; set; }
        public virtual ICollection<tbHorarioProfesores> tbHorarioProfesoresHoPr_HoraInicioNavigation { get; set; }
    }
}