// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbMatriculas
    {
        /// <summary>
        /// Identificador único de la matricula.
        /// </summary>
        public int? Matri_Id { get; set; }
        /// <summary>
        /// Identificador único del alumno.
        /// </summary>
        public int? Alu_Id { get; set; }
    }
}