// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbModalidades_tbCursosNiveles
    {
        public int Cun_Id { get; set; }
        public int Mda_Id { get; set; }

        public virtual tbCursosNiveles Cun { get; set; }
        public virtual tbModalidades Mda { get; set; }
    }
}
