// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;
using Gestion.Colegial.Entities.Entities.seguridad;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbModalidades
    {
        public tbModalidades()
        {
            tbAlumnos = new HashSet<tbAlumnos>();
            tbCursos_tbModalidades = new HashSet<tbCursos_tbModalidades>();
            tbModalidades_tbCursosNiveles = new HashSet<tbModalidades_tbCursosNiveles>();
        }

        /// <summary>
        /// Identificador único de la modalidad.
        /// </summary>
        public int Mda_Id { get; set; }
        /// <summary>
        /// Descripción por el cual se conoce la modalidad.
        /// </summary>
        public string Mda_Descripcion { get; set; }
        public bool Mda_EsEliminado { get; set; }
        public int Mda_UsuarioRegistra { get; set; }
        public DateTime Mda_FechaRegistra { get; set; }
        public int? Mda_UsuarioModifica { get; set; }
        public DateTime? Mda_FechaModifica { get; set; }

        public virtual tbUsuarios Mda_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Mda_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        public virtual ICollection<tbCursos_tbModalidades> tbCursos_tbModalidades { get; set; }
        public virtual ICollection<tbModalidades_tbCursosNiveles> tbModalidades_tbCursosNiveles { get; set; }
    }
}
