// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class tbModalidad_tbDias
    {
        public int Mdia_Id { get; set; }
        public int? Mda_Id { get; set; }
        public int? Dia_Id { get; set; }

        public virtual tbDias Dia { get; set; }
        public virtual tbModalidades Mda { get; set; }
    }
}