// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Estos son los niveles de educación con los que se cuenta, en cada nivel se culmina un ciclo para el alumno.
    /// </summary>
    public partial class tbNivelesEducativos
    {
        public tbNivelesEducativos()
        {
            tbAlumnos = new HashSet<tbAlumnos>();
            tbCursos = new HashSet<tbCursos>();
            tbCursosNiveles = new HashSet<tbCursosNiveles>();
        }

        /// <summary>
        /// Identificador único de un nivel educativo.
        /// </summary>
        public int Niv_Id { get; set; }
        /// <summary>
        /// Información de el nivel del alumno.
        /// </summary>
        public string Niv_Descripcion { get; set; }
        /// <summary>
        /// Indica si el nivel educativo está activo (1) o no (0).
        /// </summary>
        public bool Niv_EsActivo { get; set; }
        /// <summary>
        /// Indica si el nivel educativo ha sido eliminado (1) o no (0).
        /// </summary>
        public bool Niv_EsEliminado { get; set; }
        /// <summary>
        /// Identificador del usuario que registró el nivel educativo.
        /// </summary>
        public int Niv_UsuarioRegistra { get; set; }
        /// <summary>
        /// Fecha y hora de registro del nivel educativo.
        /// </summary>
        public DateTime Niv_FechaRegistra { get; set; }
        /// <summary>
        /// Identificador del usuario que modificó el nivel educativo.
        /// </summary>
        public int? Niv_UsuarioModifica { get; set; }
        /// <summary>
        /// Fecha y hora de modificación del nivel educativo.
        /// </summary>
        public DateTime? Niv_FechaModifica { get; set; }

        public virtual tbUsuarios Niv_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Niv_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        public virtual ICollection<tbCursos> tbCursos { get; set; }
        public virtual ICollection<tbCursosNiveles> tbCursosNiveles { get; set; }
    }
}