// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Gestion.Colegial.Entities.Entities.app;
using Gestion.Colegial.Entities.Entities.seguridad;

namespace Gestion.Colegial.Entities.Entities.app
{
    public partial class tbNotas
    {
        public int Not_Id { get; set; }
        public int Not_Nota { get; set; }
        public int Mat_Id { get; set; }
        public int Sem_Id { get; set; }
        public int Pac_Id { get; set; }
        public DateTime Not_Año { get; set; }
        public bool? Not_EsActivo { get; set; }
        public bool Not_EsEliminado { get; set; }
        public int Not_UsuarioRegistra { get; set; }
        public DateTime Not_FechaRegistra { get; set; }
        public int? Not_UsuarioModifica { get; set; }
        public DateTime? Not_FechaModifica { get; set; }

        public virtual tbMaterias Mat { get; set; }
        public virtual tbUsuarios Not_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Not_UsuarioRegistraNavigation { get; set; }
        public virtual tbParciales Pac { get; set; }
        public virtual tbSemestres Sem { get; set; }
    }
}
