// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Relación entre el encargado legal y el alumno.
    /// </summary>
    public partial class tbParentescos
    {
        public tbParentescos()
        {
            tbEncargados_tbAlumnos = new HashSet<tbEncargados_tbAlumnos>();
        }

        /// <summary>
        /// Identificador único de un parentesco.
        /// </summary>
        public int Par_Id { get; set; }
        /// <summary>
        /// Descripción sobre el parentesco sangíneo o no sangíneo del encargado.
        /// </summary>
        public string Par_Descripcion { get; set; }
        /// <summary>
        /// Indica si el parentesco ha sido eliminado (1) o no (0).
        /// </summary>
        public bool Par_EsEliminado { get; set; }
        /// <summary>
        /// Identificador del usuario que registró el parentesco.
        /// </summary>
        public int Par_UsuarioRegistra { get; set; }
        /// <summary>
        /// Fecha y hora de registro del parentesco.
        /// </summary>
        public DateTime Par_FechaRegistra { get; set; }
        /// <summary>
        /// Identificador del usuario que modificó el parentesco.
        /// </summary>
        public int? Par_UsuarioModifica { get; set; }
        /// <summary>
        /// Fecha y hora de modificación del parentesco.
        /// </summary>
        public DateTime? Par_FechaModifica { get; set; }

        public virtual tbUsuarios Par_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Par_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbEncargados_tbAlumnos> tbEncargados_tbAlumnos { get; set; }
    }
}