// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Registra la cantidad de secciones que puede haber en el centro estudiantil.
    /// </summary>
    public partial class tbSecciones
    {
        public tbSecciones()
        {
            tbAlumnos = new HashSet<tbAlumnos>();
            tbCursos_tbSecciones = new HashSet<tbCursos_tbSecciones>();
            tbHorarioAlumnos = new HashSet<tbHorarioAlumnos>();
            tbHorarioProfesores = new HashSet<tbHorarioProfesores>();
        }

        /// <summary>
        /// Identificador único de la sección.
        /// </summary>
        public int Sec_Id { get; set; }
        /// <summary>
        /// Nombre de la sección.
        /// </summary>
        public string Sec_Descripcion { get; set; }
        /// <summary>
        /// Indica si la sección ha sido eliminada (1) o no (0).
        /// </summary>
        public bool Sec_EsEliminado { get; set; }
        /// <summary>
        /// Identificador del usuario que registró la sección.
        /// </summary>
        public int Sec_UsuarioRegistra { get; set; }
        /// <summary>
        /// Fecha y hora de registro de la sección.
        /// </summary>
        public DateTime Sec_FechaRegistra { get; set; }
        /// <summary>
        /// Identificador del usuario que modificó la sección.
        /// </summary>
        public int? Sec_UsuarioModifica { get; set; }
        /// <summary>
        /// Fecha y hora de modificación de la sección.
        /// </summary>
        public DateTime? Sec_FechaModifica { get; set; }

        public virtual tbUsuarios Sec_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Sec_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnos { get; set; }
        public virtual ICollection<tbCursos_tbSecciones> tbCursos_tbSecciones { get; set; }
        public virtual ICollection<tbHorarioAlumnos> tbHorarioAlumnos { get; set; }
        public virtual ICollection<tbHorarioProfesores> tbHorarioProfesores { get; set; }
    }
}