// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Información del título.
    /// </summary>
    public partial class tbTitulos
    {
        public tbTitulos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        /// <summary>
        /// Identificador único del titulo.
        /// </summary>
        public int Tit_Id { get; set; }
        /// <summary>
        /// Nombre que tiene el titulo.
        /// </summary>
        public string Tit_Descripcion { get; set; }
        /// <summary>
        /// Indica si el título ha sido eliminado (1) o no (0).
        /// </summary>
        public bool Tit_EsEliminado { get; set; }
        /// <summary>
        /// Identificador del usuario que registró el título.
        /// </summary>
        public int Tit_UsuarioRegistra { get; set; }
        /// <summary>
        /// Fecha y hora de registro del título.
        /// </summary>
        public DateTime Tit_FechaRegistra { get; set; }
        /// <summary>
        /// Identificador del usuario que modificó el título.
        /// </summary>
        public int? Tit_UsuarioModifica { get; set; }
        /// <summary>
        /// Fecha y hora de modificación del título.
        /// </summary>
        public DateTime? Tit_FechaModifica { get; set; }

        public virtual tbUsuarios Tit_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Tit_UsuarioRegistraNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}