// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Business.Dtos
{
    public partial class AlumnosFindDto
    {
        public int? Niv_Id { get; set; }
        public string Niv_Descripcion { get; set; }
        public int? Cun_Id { get; set; }
        public string Cun_Descripcion { get; set; }
        public int? Mda_Id { get; set; }
        public string Mda_Descripcion { get; set; }
        public int Cur_Id { get; set; }
        public string Cur_Nombre { get; set; }
        public int? Sec_Id { get; set; }
        public string Sec_Descripcion { get; set; }
        public int Est_Id { get; set; }
        public string Est_Descripcion { get; set; }
        public int Alu_Id { get; set; }
        public int Per_Id { get; set; }
        public string Per_Identidad { get; set; }
        public string Per_PrimerNombre { get; set; }
        public string Per_SegundoNombre { get; set; }
        public string Per_ApellidoPaterno { get; set; }
        public string Per_ApellidoMaterno { get; set; }
        public DateTime Per_FechaNacimiento { get; set; }
        public string Per_CorreoElectronico { get; set; }
        public string Per_Telefono { get; set; }
        public string Per_Direccion { get; set; }
        public string Per_Sexo { get; set; }
        public bool Per_EsActivo { get; set; }
        public bool Per_EsEliminado { get; set; }
        public int Per_UsuarioRegistra { get; set; }
        public DateTime? Per_FechaRegistra { get; set; }
        public int Per_UsuarioModifica { get; set; }
        public DateTime? Per_FechaModifica { get; set; }
    }
}
