// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Business.Dtos
{
    public partial class CursosDto
    {
        public int Cur_Id { get; set; }
        public string Cur_Nombre { get; set; }
        public int Niv_Id { get; set; }
        public string Niv_Descripcion { get; set; }
        public bool Cur_EsActivo { get; set; }
        public int Cur_UsuarioRegistra { get; set; }
        public DateTime? Cur_FechaRegistra { get; set; }
        public int Cur_UsuarioModifica { get; set; }
        public DateTime? Cur_FechaModifica { get; set; }
    }
}
