// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Business.Dtos
{
    public partial class EmpleadosDto1
    {
        public int? Emp_Id { get; set; }
        public string Emp_Codigo { get; set; }
        public string Per_Identidad { get; set; }
        public string Per_PrimerNombre { get; set; }
        public string Per_SegundoNombre { get; set; }
        public string Per_ApellidoPaterno { get; set; }
        public string Per_ApellidoMaterno { get; set; }
        public DateTime? Per_FechaNacimiento { get; set; }
        public string Per_CorreoElectronico { get; set; }
        public string Per_Telefono { get; set; }
        public string Per_Direccion { get; set; }
        public string Per_Sexo { get; set; }
        public string EsActivo { get; set; }
        public int Emp_UsuarioRegistra { get; set; }
        public string Emp_UsuarioRegistraNombre { get; set; }
        public DateTime? Per_FechaRegistra { get; set; }
        public int Emp_UsuarioModifica { get; set; }
        public string Emp_UsuarioModificaNombre { get; set; }
        public DateTime? Per_FechaModifica { get; set; }
        public string Tit_Descripcion { get; set; }
        public string Car_Descripcion { get; set; }
    }
}
