// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Business.Dtos
{
    public partial class EncargadosFindDto
    {
        public int Enc_Id { get; set; }
        public int Per_Id { get; set; }
        public string Per_Identidad { get; set; }
        public string Per_PrimerNombre { get; set; }
        public string Per_SegundoNombre { get; set; }
        public string Per_ApellidoPaterno { get; set; }
        public string Per_ApellidoMaterno { get; set; }
        public DateTime Per_FechaNacimiento { get; set; }
        public string Per_CorreoElectronico { get; set; }
        public string Per_Telefono { get; set; }
        public string Per_Direccion { get; set; }
        public string Per_Sexo { get; set; }
        public bool Per_EsActivo { get; set; }
        public string Enc_Ocupacion { get; set; }
        public int Per_UsuarioRegistra { get; set; }
        public DateTime? Per_FechaRegistra { get; set; }
        public int Per_UsuarioModifica { get; set; }
        public DateTime? Per_FechaModifica { get; set; }
    }
}
