// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Business.Dtos
{
    public partial class NotasDto
    {
        public int Not_Id { get; set; }
        public int Not_Nota { get; set; }
        public string Mat_Nombre { get; set; }
        public string Sem_Descripcion { get; set; }
        public string Pac_Descripcion { get; set; }
        public DateTime Not_Año { get; set; }
        public bool Not_EsActivo { get; set; }
        public int Not_UsuarioRegistra { get; set; }
        public DateTime? Not_FechaRegistra { get; set; }
        public int Not_UsuarioModifica { get; set; }
        public DateTime? Not_FechaModifica { get; set; }
    }
}
