// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene los conceptos de pago disponibles (mensualidad, matrícula, etc.)
    /// </summary>
    public partial class tbConceptosPago
    {
        public tbConceptosPago()
        {
            tbTarifas = new HashSet<tbTarifas>();
            tbCuentasCobrar = new HashSet<tbCuentasCobrar>();
        }

        /// <summary>
        /// Identificador único del concepto de pago.
        /// </summary>
        public int Cpa_Id { get; set; }
        /// <summary>
        /// Descripción del concepto de pago.
        /// </summary>
        public string Cpa_Descripcion { get; set; }
        /// <summary>
        /// Indica si el concepto es recurrente (mensualidad, etc.)
        /// </summary>
        public bool Cpa_EsRecurrente { get; set; }
        /// <summary>
        /// Indica si el concepto es obligatorio.
        /// </summary>
        public bool Cpa_EsObligatorio { get; set; }
        /// <summary>
        /// Indica si el concepto está activo.
        /// </summary>
        public bool Cpa_EsActivo { get; set; }
        public bool Cpa_EsEliminado { get; set; }
        public int Cpa_UsuarioRegistra { get; set; }
        public DateTime Cpa_FechaRegistra { get; set; }
        public int? Cpa_UsuarioModifica { get; set; }
        public DateTime? Cpa_FechaModifica { get; set; }

        public virtual ICollection<tbTarifas> tbTarifas { get; set; }
        public virtual ICollection<tbCuentasCobrar> tbCuentasCobrar { get; set; }
    }
}
