// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene las cuentas por cobrar de cada alumno.
    /// </summary>
    public partial class tbCuentasCobrar
    {
        public tbCuentasCobrar()
        {
            tbDescuentosAplicados = new HashSet<tbDescuentosAplicados>();
            tbMoratorias = new HashSet<tbMoratorias>();
            tbPagosDetalle = new HashSet<tbPagosDetalle>();
        }

        /// <summary>
        /// Identificador único de la cuenta por cobrar.
        /// </summary>
        public int Cco_Id { get; set; }
        /// <summary>
        /// Identificador del alumno.
        /// </summary>
        public int Alu_Id { get; set; }
        /// <summary>
        /// Identificador del concepto de pago.
        /// </summary>
        public int Cpa_Id { get; set; }
        /// <summary>
        /// Identificador de la tarifa aplicada.
        /// </summary>
        public int? Tar_Id { get; set; }
        /// <summary>
        /// Monto original de la cuenta.
        /// </summary>
        public decimal Cco_MontoOriginal { get; set; }
        /// <summary>
        /// Monto del descuento aplicado.
        /// </summary>
        public decimal Cco_MontoDescuento { get; set; }
        /// <summary>
        /// Monto de la mora acumulada.
        /// </summary>
        public decimal Cco_MontoMora { get; set; }
        /// <summary>
        /// Monto total a pagar (original - descuento + mora).
        /// </summary>
        public decimal Cco_MontoTotal { get; set; }
        /// <summary>
        /// Monto pendiente de pago.
        /// </summary>
        public decimal Cco_MontoPendiente { get; set; }
        /// <summary>
        /// Fecha de emisión de la cuenta.
        /// </summary>
        public DateTime Cco_FechaEmision { get; set; }
        /// <summary>
        /// Fecha de vencimiento de la cuenta.
        /// </summary>
        public DateTime Cco_FechaVencimiento { get; set; }
        /// <summary>
        /// Identificador del estado de pago.
        /// </summary>
        public int Epa_Id { get; set; }
        /// <summary>
        /// Observaciones adicionales.
        /// </summary>
        public string Cco_Observaciones { get; set; }
        public bool Cco_EsEliminado { get; set; }
        public int Cco_UsuarioRegistra { get; set; }
        public DateTime Cco_FechaRegistra { get; set; }
        public int? Cco_UsuarioModifica { get; set; }
        public DateTime? Cco_FechaModifica { get; set; }

        public virtual tbConceptosPago Cpa { get; set; }
        public virtual tbTarifas Tar { get; set; }
        public virtual tbEstadosPago Epa { get; set; }
        public virtual ICollection<tbDescuentosAplicados> tbDescuentosAplicados { get; set; }
        public virtual ICollection<tbMoratorias> tbMoratorias { get; set; }
        public virtual ICollection<tbPagosDetalle> tbPagosDetalle { get; set; }
    }
}
