// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene los descuentos disponibles (becas, promociones, etc.)
    /// </summary>
    public partial class tbDescuentos
    {
        public tbDescuentos()
        {
            tbDescuentosAplicados = new HashSet<tbDescuentosAplicados>();
        }

        /// <summary>
        /// Identificador único del descuento.
        /// </summary>
        public int Des_Id { get; set; }
        /// <summary>
        /// Descripción del descuento.
        /// </summary>
        public string Des_Descripcion { get; set; }
        /// <summary>
        /// Tipo de descuento: 'P' = Porcentaje, 'M' = Monto fijo.
        /// </summary>
        public string Des_TipoDescuento { get; set; }
        /// <summary>
        /// Valor del descuento (porcentaje o monto).
        /// </summary>
        public decimal Des_Valor { get; set; }
        /// <summary>
        /// Indica si el descuento está activo.
        /// </summary>
        public bool Des_EsActivo { get; set; }
        public bool Des_EsEliminado { get; set; }
        public int Des_UsuarioRegistra { get; set; }
        public DateTime Des_FechaRegistra { get; set; }
        public int? Des_UsuarioModifica { get; set; }
        public DateTime? Des_FechaModifica { get; set; }

        public virtual ICollection<tbDescuentosAplicados> tbDescuentosAplicados { get; set; }
    }
}
