// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene los descuentos aplicados a cada cuenta por cobrar.
    /// </summary>
    public partial class tbDescuentosAplicados
    {
        /// <summary>
        /// Identificador único del descuento aplicado.
        /// </summary>
        public int Dap_Id { get; set; }
        /// <summary>
        /// Identificador de la cuenta por cobrar.
        /// </summary>
        public int Cco_Id { get; set; }
        /// <summary>
        /// Identificador del descuento.
        /// </summary>
        public int Des_Id { get; set; }
        /// <summary>
        /// Monto del descuento aplicado.
        /// </summary>
        public decimal Dap_MontoAplicado { get; set; }
        /// <summary>
        /// Justificación del descuento.
        /// </summary>
        public string Dap_Justificacion { get; set; }
        public bool Dap_EsEliminado { get; set; }
        public int Dap_UsuarioRegistra { get; set; }
        public DateTime Dap_FechaRegistra { get; set; }
        public int? Dap_UsuarioModifica { get; set; }
        public DateTime? Dap_FechaModifica { get; set; }

        public virtual tbCuentasCobrar Cco { get; set; }
        public virtual tbDescuentos Des { get; set; }
    }
}
