// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene los estados de pago (pendiente, pagado, vencido, etc.)
    /// </summary>
    public partial class tbEstadosPago
    {
        public tbEstadosPago()
        {
            tbCuentasCobrar = new HashSet<tbCuentasCobrar>();
        }

        /// <summary>
        /// Identificador único del estado de pago.
        /// </summary>
        public int Epa_Id { get; set; }
        /// <summary>
        /// Descripción del estado de pago.
        /// </summary>
        public string Epa_Descripcion { get; set; }
        public bool Epa_EsEliminado { get; set; }
        public int Epa_UsuarioRegistra { get; set; }
        public DateTime Epa_FechaRegistra { get; set; }
        public int? Epa_UsuarioModifica { get; set; }
        public DateTime? Epa_FechaModifica { get; set; }

        public virtual ICollection<tbCuentasCobrar> tbCuentasCobrar { get; set; }
    }
}
