// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene las formas de pago disponibles (efectivo, tarjeta, transferencia, etc.)
    /// </summary>
    public partial class tbFormasPago
    {
        public tbFormasPago()
        {
            tbPagos = new HashSet<tbPagos>();
        }

        /// <summary>
        /// Identificador único de la forma de pago.
        /// </summary>
        public int Fpa_Id { get; set; }
        /// <summary>
        /// Descripción de la forma de pago.
        /// </summary>
        public string Fpa_Descripcion { get; set; }
        /// <summary>
        /// Indica si la forma de pago está activa.
        /// </summary>
        public bool Fpa_EsActivo { get; set; }
        public bool Fpa_EsEliminado { get; set; }
        public int Fpa_UsuarioRegistra { get; set; }
        public DateTime Fpa_FechaRegistra { get; set; }
        public int? Fpa_UsuarioModifica { get; set; }
        public DateTime? Fpa_FechaModifica { get; set; }

        public virtual ICollection<tbPagos> tbPagos { get; set; }
    }
}
