// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene las moratorias aplicadas a cuentas vencidas.
    /// </summary>
    public partial class tbMoratorias
    {
        /// <summary>
        /// Identificador único de la moratoria.
        /// </summary>
        public int Mor_Id { get; set; }
        /// <summary>
        /// Identificador de la cuenta por cobrar.
        /// </summary>
        public int Cco_Id { get; set; }
        /// <summary>
        /// Días de atraso en el pago.
        /// </summary>
        public int Mor_DiasAtraso { get; set; }
        /// <summary>
        /// Porcentaje de mora aplicado.
        /// </summary>
        public decimal Mor_Porcentaje { get; set; }
        /// <summary>
        /// Monto de la mora calculada.
        /// </summary>
        public decimal Mor_MontoMora { get; set; }
        /// <summary>
        /// Fecha de cálculo de la mora.
        /// </summary>
        public DateTime Mor_FechaCalculo { get; set; }
        public bool Mor_EsEliminado { get; set; }
        public int Mor_UsuarioRegistra { get; set; }
        public DateTime Mor_FechaRegistra { get; set; }
        public int? Mor_UsuarioModifica { get; set; }
        public DateTime? Mor_FechaModifica { get; set; }

        public virtual tbCuentasCobrar Cco { get; set; }
    }
}
