// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene el detalle de distribución de cada pago a las cuentas por cobrar.
    /// </summary>
    public partial class tbPagosDetalle
    {
        /// <summary>
        /// Identificador único del detalle de pago.
        /// </summary>
        public int Pde_Id { get; set; }
        /// <summary>
        /// Identificador del pago.
        /// </summary>
        public int Pag_Id { get; set; }
        /// <summary>
        /// Identificador de la cuenta por cobrar.
        /// </summary>
        public int Cco_Id { get; set; }
        /// <summary>
        /// Monto aplicado a esta cuenta.
        /// </summary>
        public decimal Pde_MontoAplicado { get; set; }
        public bool Pde_EsEliminado { get; set; }
        public int Pde_UsuarioRegistra { get; set; }
        public DateTime Pde_FechaRegistra { get; set; }
        public int? Pde_UsuarioModifica { get; set; }
        public DateTime? Pde_FechaModifica { get; set; }

        public virtual tbPagos Pag { get; set; }
        public virtual tbCuentasCobrar Cco { get; set; }
    }
}
