// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene los pagos realizados por los alumnos o encargados.
    /// </summary>
    public partial class tbPagos
    {
        public tbPagos()
        {
            tbPagosDetalle = new HashSet<tbPagosDetalle>();
            tbRecibos = new HashSet<tbRecibos>();
        }

        /// <summary>
        /// Identificador único del pago.
        /// </summary>
        public int Pag_Id { get; set; }
        /// <summary>
        /// Identificador del alumno.
        /// </summary>
        public int Alu_Id { get; set; }
        /// <summary>
        /// Identificador del encargado que realiza el pago.
        /// </summary>
        public int? Enc_Id { get; set; }
        /// <summary>
        /// Identificador de la forma de pago.
        /// </summary>
        public int Fpa_Id { get; set; }
        /// <summary>
        /// Monto total del pago.
        /// </summary>
        public decimal Pag_MontoTotal { get; set; }
        /// <summary>
        /// Fecha y hora del pago.
        /// </summary>
        public DateTime Pag_FechaPago { get; set; }
        /// <summary>
        /// Número de referencia del pago (cheque, transferencia, etc.)
        /// </summary>
        public string Pag_NumeroReferencia { get; set; }
        /// <summary>
        /// Observaciones adicionales del pago.
        /// </summary>
        public string Pag_Observaciones { get; set; }
        /// <summary>
        /// Identificador del usuario que registra el pago.
        /// </summary>
        public int Usu_Id { get; set; }
        public bool Pag_EsEliminado { get; set; }
        public int Pag_UsuarioRegistra { get; set; }
        public DateTime Pag_FechaRegistra { get; set; }
        public int? Pag_UsuarioModifica { get; set; }
        public DateTime? Pag_FechaModifica { get; set; }

        public virtual tbFormasPago Fpa { get; set; }
        public virtual ICollection<tbPagosDetalle> tbPagosDetalle { get; set; }
        public virtual ICollection<tbRecibos> tbRecibos { get; set; }
    }
}
