// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene los recibos generados para cada pago.
    /// </summary>
    public partial class tbRecibos
    {
        /// <summary>
        /// Identificador único del recibo.
        /// </summary>
        public int Rec_Id { get; set; }
        /// <summary>
        /// Identificador del pago asociado.
        /// </summary>
        public int Pag_Id { get; set; }
        /// <summary>
        /// Número de recibo generado.
        /// </summary>
        public string Rec_NumeroRecibo { get; set; }
        /// <summary>
        /// Fecha y hora de emisión del recibo.
        /// </summary>
        public DateTime Rec_FechaEmision { get; set; }
        /// <summary>
        /// Ruta al archivo PDF del recibo.
        /// </summary>
        public string Rec_RutaArchivo { get; set; }
        public bool Rec_EsEliminado { get; set; }
        public int Rec_UsuarioRegistra { get; set; }
        public DateTime Rec_FechaRegistra { get; set; }
        public int? Rec_UsuarioModifica { get; set; }
        public DateTime? Rec_FechaModifica { get; set; }

        public virtual tbPagos Pag { get; set; }
    }
}
