// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities
{
    /// <summary>
    /// Contiene las tarifas asociadas a cada concepto de pago según nivel o curso.
    /// </summary>
    public partial class tbTarifas
    {
        public tbTarifas()
        {
            tbCuentasCobrar = new HashSet<tbCuentasCobrar>();
        }

        /// <summary>
        /// Identificador único de la tarifa.
        /// </summary>
        public int Tar_Id { get; set; }
        /// <summary>
        /// Identificador del concepto de pago.
        /// </summary>
        public int Cpa_Id { get; set; }
        /// <summary>
        /// Identificador del nivel educativo (opcional).
        /// </summary>
        public int? Niv_Id { get; set; }
        /// <summary>
        /// Identificador del curso/nivel (opcional).
        /// </summary>
        public int? Cun_Id { get; set; }
        /// <summary>
        /// Monto de la tarifa.
        /// </summary>
        public decimal Tar_Monto { get; set; }
        /// <summary>
        /// Año de vigencia de la tarifa.
        /// </summary>
        public short Tar_AnioVigencia { get; set; }
        public bool Tar_EsEliminado { get; set; }
        public int Tar_UsuarioRegistra { get; set; }
        public DateTime Tar_FechaRegistra { get; set; }
        public int? Tar_UsuarioModifica { get; set; }
        public DateTime? Tar_FechaModifica { get; set; }

        public virtual tbConceptosPago Cpa { get; set; }
        public virtual ICollection<tbCuentasCobrar> tbCuentasCobrar { get; set; }
    }
}
