// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class ObtenerCantidadAlumnosResult
    {
        public string NivelEducativo { get; set; }
        public string Curso { get; set; }
        public string Modalida { get; set; }
        public string secciones { get; set; }
        public int? CantidadAlumnos { get; set; }
    }
}
