// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_ObtenerPromedioCursoUltimosAnios_DashboardResult
    {
        public int? AnioCursado { get; set; }
        [Column("PromedioAnual", TypeName = "decimal(38,6)")]
        public decimal? PromedioAnual { get; set; }
    }
}
