// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbSecciones_DetailResult
    {
        public int? Sec_Id { get; set; }
        public string Sec_Descripcion { get; set; }
        public string Sec_UsuarioRegistraNombre { get; set; }
        public DateTime? Sec_FechaRegistra { get; set; }
        public string Sec_UsuarioModificaNombre { get; set; }
        public DateTime? Sec_FechaModifica { get; set; }
    }
}
