// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbCursos_DetailResult
    {
        public int? Cur_Id { get; set; }
        public string Cur_Nombre { get; set; }
        public string Aul_Descripcion { get; set; }
        public string Sec_Descripcion { get; set; }
        public string Niv_Descripcion { get; set; }
        public string Mda_Descripcion { get; set; }
        public string Cur_EsActivo { get; set; }
        public string Cur_UsuarioRegistraNombre { get; set; }
        public DateTime? Cur_FechaRegistra { get; set; }
        public string Cur_UsuarioModificaNombre { get; set; }
        public DateTime? Cur_FechaModifica { get; set; }
    }
}
