// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCursos_tbSecciones_FindResult
    {
        public int Sec_Id { get; set; }
        public string Sec_Descripcion { get; set; }
    }
}
