// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbHorarioAlumnos_ListResult
    {
        public int HoAl_Id { get; set; }
        public string Cur_Nombre { get; set; }
        public string Cun_Descripcion { get; set; }
        public string Mat_Nombre { get; set; }
        public string Hor_Hora { get; set; }
        public string Dia_Descripcion { get; set; }
    }
}
