// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCargos_ExistResult
    {
        public int Car_Id { get; set; }
        public string Car_Descripcion { get; set; }
    }
}
