// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbNotas_ListResult
    {
        public int Not_Id { get; set; }
        public int Not_Nota { get; set; }
        public string Mat_Nombre { get; set; }
        public string Sem_Descripcion { get; set; }
        public string Pac_Descripcion { get; set; }
        public DateTime Not_Año { get; set; }
        public string EsActivo { get; set; }
    }
}
