// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbDias_DetailResult
    {
        public int? Dia_Id { get; set; }
        public string Dia_Descripcion { get; set; }
        public string Dia_UsuarioRegistraNombre { get; set; }
        public DateTime? Dia_FechaRegistra { get; set; }
        public string Dia_UsuarioModificaNombre { get; set; }
        public DateTime? Dia_FechaModifica { get; set; }
    }
}
