// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbAlumnos_ListResult
    {
        public int Alu_Id { get; set; }
        public string Per_Imagen { get; set; }
        public string Per_Identidad { get; set; }
        public string Alu_Nombre { get; set; }
        public string Cno_Descripcion { get; set; }
        public string Mda_Descripcion { get; set; }
        public string Sec_Descripcion { get; set; }
        public string Niv_Descripcion { get; set; }
        public int? AnioCursado { get; set; }
        public string Est_Descripcion { get; set; }
    }
}
