// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbHoras_ExistResult
    {
        public int Hor_Id { get; set; }
        public string Hor_Hora { get; set; }
    }
}
