// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbEstados_DropdownResult
    {
        public int Est_Id { get; set; }
        public string Est_Descripcion { get; set; }
    }
}
