// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbModalidades_DetailResult
    {
        public int? Mda_Id { get; set; }
        public string Mda_Descripcion { get; set; }
        public string Mda_UsuarioRegistraNombre { get; set; }
        public DateTime? Mda_FechaRegistra { get; set; }
        public string Mda_UsuarioModificaNombre { get; set; }
        public DateTime? Mda_FechaModifica { get; set; }
    }
}
