// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbEventos_FindResult
    {
        public int even_Id { get; set; }
        public string even_Nombre { get; set; }
        public string even_Informacion { get; set; }
        public DateTime even_Fecha { get; set; }
        public TimeSpan even_Hora { get; set; }
        public bool even_Concluido { get; set; }
        public int even_UsuarioRegistra { get; set; }
        public DateTime even_FechaRegistra { get; set; }
        public int? even_UsuarioModifica { get; set; }
        public DateTime? even_FechaModifica { get; set; }
    }
}
