// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbCursosNombres_DetailResult
    {
        public string Cno_Id { get; set; }
        public string Cno_Descripcion { get; set; }
        public string Cno_UsuarioRegistraNombre { get; set; }
        public DateTime? Cno_FechaRegistra { get; set; }
        public string Cno_UsuarioModificaNombre { get; set; }
        public DateTime? Cno_FechaModifica { get; set; }
    }
}
