// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbAulas_DetailResult
    {
        public int? Aul_Id { get; set; }
        public string Aul_Descripcion { get; set; }
        public string Aul_UsuarioRegistraNombre { get; set; }
        public DateTime? Aul_FechaRegistra { get; set; }
        public string Aul_UsuarioModificaNombre { get; set; }
        public DateTime? Aul_FechaModifica { get; set; }
    }
}
