// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCursosNiveles_ExistResult
    {
        public int Cun_Id { get; set; }
        public string Cun_Descripcion { get; set; }
    }
}
