// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbSemestres_FindResult
    {
        public int Sem_Id { get; set; }
        public string Sem_Descripcion { get; set; }
        public bool Sem_EsActivo { get; set; }
    }
}
