// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbEncargados_ListResult
    {
        public int Enc_Id { get; set; }
        public string Per_Identidad { get; set; }
        public string Enc_Nombre { get; set; }
        public string Per_Telefono { get; set; }
        public string Enc_Ocupacion { get; set; }
        public string EsActivo { get; set; }
    }
}
