// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbDuraciones_FindResult
    {
        public int Dur_Id { get; set; }
        public string Dur_Descripcion { get; set; }
    }
}
