// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbModalidades_By_tbCursosNiveles_DropdownResult
    {
        public int Mda_Id { get; set; }
        public string Mda_Descripcion { get; set; }
    }
}
