// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbTitulos_DetailResult
    {
        public int? Tit_Id { get; set; }
        public string Tit_Descripcion { get; set; }
        public string Tit_UsuarioRegistraNombre { get; set; }
        public DateTime? Tit_FechaRegistra { get; set; }
        public string Tit_UsuarioModificaNombre { get; set; }
        public DateTime? Tit_FechaModifica { get; set; }
    }
}
