// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbNivelesEducativos_DetailResult
    {
        public int? Niv_Id { get; set; }
        public string Niv_Descripcion { get; set; }
        public string Niv_EsActivo { get; set; }
        public string Niv_UsuarioRegistraNombre { get; set; }
        public DateTime? Niv_FechaRegistra { get; set; }
        public string Niv_UsuarioModificaNombre { get; set; }
        public DateTime? Niv_FechaModifica { get; set; }
    }
}
