// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbEmpleados_ListResult
    {
        public int Emp_Id { get; set; }
        public string Emp_Codigo { get; set; }
        public string Emp_Nombre { get; set; }
        public string EsActivo { get; set; }
        public string Tit_Descripcion { get; set; }
        public string Car_Descripcion { get; set; }
    }
}
