// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbParentescos_DetailResult
    {
        public int? Par_Id { get; set; }
        public string Par_Descripcion { get; set; }
        public string Par_UsuarioRegistraNombre { get; set; }
        public DateTime? Par_FechaRegistra { get; set; }
        public string Par_UsuarioModificaNombre { get; set; }
        public DateTime? Par_FechaModifica { get; set; }
    }
}
