// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class PR_tbAlumnos_DetailResult
    {
        public int? Alu_Id { get; set; }
        public string Per_Identidad { get; set; }
        public string Per_PrimerNombre { get; set; }
        public string Per_SegundoNombre { get; set; }
        public string Per_ApellidoPaterno { get; set; }
        public string Per_ApellidoMaterno { get; set; }
        public DateTime? Per_FechaNacimiento { get; set; }
        public string Per_CorreoElectronico { get; set; }
        public string Per_Telefono { get; set; }
        public string Per_Direccion { get; set; }
        public string Per_Sexo { get; set; }
        public string Cur_Nombre { get; set; }
        public string Est_Descripcion { get; set; }
        public string Niv_Descripcion { get; set; }
        public string Mda_Descripcion { get; set; }
        public string Cun_Descripcion { get; set; }
        public string Sec_Descripcion { get; set; }
        public string Per_EsActivo { get; set; }
        public string Alu_UsuarioRegistraNombre { get; set; }
        public DateTime? Per_FechaRegistra { get; set; }
        public string Alu_UsuarioModificaNombre { get; set; }
        public DateTime? Per_FechaModifica { get; set; }
    }
}
