// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.Entities
{
    public partial class PR_tbCursos_DropdownResult
    {
        public int Cur_Id { get; set; }
        public string Cur_Nombre { get; set; }
    }
}
