// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.Entities.dbo
{
    public partial class tbEventoError
    {
        public int? Err_Id { get; set; }
        public string Err_NombreArchivo { get; set; }
        public DateTime? Err_Fecha { get; set; }
        public string Err_Ruta { get; set; }
        public string Err_Message { get; set; }
        public string Err_InnerException { get; set; }
    }
}
