<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\AlumnosDetailDto.cs" />
    <Compile Remove="Dtos\AlumnosFindDto.cs" />
    <Compile Remove="Extensions\CustomMapping.cs" />
    <Compile Remove="Services\EmpleadoService.cs" />
    <Compile Remove="Services\EncargadoService.cs" />
    <Compile Remove="Services\EventoService.cs" />
    <Compile Remove="Services\HoraService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="Serilog" Version="2.12.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gestion.Colegial.DataAccess\Gestion.Colegial.DataAccess.csproj" />
    <ProjectReference Include="..\Gestion.Colegial.Entities\Gestion.Colegial.Entities.csproj" />
  </ItemGroup>

</Project>
