// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class CardsInHomeDashboardDto
    {
        public int? Graduados { get; set; }
        public int? DiferenciaPromedioAnual { get; set; }
        public int? ActualPromedioAnual { get; set; }
        public int? DiferenciaNuevoIngreso { get; set; }
    }
}
