// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class DiferenciaEntreCantidadAlumnosAnioPasadoDashboardDto
    {
        public string NombreCurso { get; set; }
        public int? CantidadAlumnos { get; set; }
        public int? CantidadAnterior { get; set; }
        public int PorcentajeDiferencia { get; set; }
    }
}
