// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class ObtenerPromedioCursoUltimosAniosDashboardDto
    {
        public int? AnioCursado { get; set; }
        [Column("PromedioAnual", TypeName = "decimal(38,6)")]
        public decimal? PromedioAnual { get; set; }
    }
}
