// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class CursoNivelDetailDto
    {
        public int? CursoNivelId { get; set; }
        public string DescripcionCursoNivel { get; set; }
        public string NombreUsuarioRegistraCursoNivel { get; set; }
        public DateTime? FechaRegistroCursoNivel { get; set; }
        public string NombreUsuarioModificaCursoNivel { get; set; }
        public DateTime? FechaModificacionCursoNivel { get; set; }
    }
}
