// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class CargoDetailDto
    {
        public int? CargoId { get; set; }
        public string DescripcionCargo { get; set; }
        public string NombreUsuarioRegistraCargo { get; set; }
        public DateTime? FechaRegistroCargo { get; set; }
        public string NombreUsuarioModificaCargo { get; set; }
        public DateTime? FechaModificacionCargo { get; set; }
    }
}
