// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class TituloDetailDto
    {
        public int? TituloId { get; set; }
        public string DescripcionTitulo { get; set; }
        public string NombreUsuarioRegistraTitulo { get; set; }
        public DateTime? FechaRegistroTitulo { get; set; }
        public string NombreUsuarioModificaTitulo { get; set; }
        public DateTime? FechaModificacionTitulo { get; set; }
    }
}
