// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class NivelEducativoDetailDto
    {
        public int? NivelId { get; set; }
        public string DescripcionNivel { get; set; }
        public string EsActivoNivel { get; set; }
        public string NombreUsuarioRegistraNivel { get; set; }
        public DateTime? FechaRegistroNivel { get; set; }
        public string NombreUsuarioModificaNivel { get; set; }
        public DateTime? FechaModificacionNivel { get; set; }
    }
}
