// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class DuracionDetailDto
    {
        public int? DuracionId { get; set; }
        public string DescripcionDuracion { get; set; }
        public string NombreUsuarioRegistraDuracion { get; set; }
        public DateTime? FechaRegistroDuracion { get; set; }
        public string NombreUsuarioModificaDuracion { get; set; }
        public DateTime? FechaModificacionDuracion { get; set; }
    }
}
