// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class ParentescoDetailDto
    {
        public int? ParentescoId { get; set; }
        public string DescripcionParentesco { get; set; }
        public string NombreUsuarioRegistraParentesco { get; set; }
        public DateTime? FechaRegistroParentesco { get; set; }
        public string NombreUsuarioModificaParentesco { get; set; }
        public DateTime? FechaModificacionParentesco { get; set; }
    }
}
