// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class EstadoDetailDto
    {
        public int? EstadoId { get; set; }
        public string DescripcionEstado { get; set; }
        public string NombreUsuarioRegistraEstado { get; set; }
        public DateTime? FechaRegistroEstado { get; set; }
        public string NombreUsuarioModificaEstado { get; set; }
        public DateTime? FechaModificacionEstado { get; set; }
    }
}
