// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class ParcialExistDto
    {
        public int ParcialId { get; set; }
        public string DescripcionParcial { get; set; }
    }
}
