// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class SeccionPorCursoDropdownDto
    {
        public int SeccionId { get; set; }
        public string DescripcionSeccion { get; set; }
    }
}
