// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class ModalidadDetailDto
    {
        public int? ModalidadId { get; set; }
        public string DescripcionModalidad { get; set; }
        public string NombreUsuarioRegistraModalidad { get; set; }
        public DateTime? FechaRegistroModalidad { get; set; }
        public string NombreUsuarioModificaModalidad { get; set; }
        public DateTime? FechaModificacionModalidad { get; set; }
    }
}
