// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class ParcialDetailDto
    {
        public int? ParcialId { get; set; }
        public string DescripcionParcial { get; set; }
        public string NombreUsuarioRegistraParcial { get; set; }
        public DateTime? FechaRegistroParcial { get; set; }
        public string NombreUsuarioModificaParcial { get; set; }
        public DateTime? FechaModificacionParcial { get; set; }
    }
}
