// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class EmpleadoListDto
    {
        public int EmpleadoId { get; set; }
        public string CodigoEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public string EsActivo { get; set; }
        public string DescripcionTitulo { get; set; }
        public string DescripcionCargo { get; set; }
    }
}
