// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class NotaFindDto
    {
        public int NotaId { get; set; }
        public int ValorNota { get; set; }
        public string NombreMateria { get; set; }
        public string DescripcionSemestre { get; set; }
        public string DescripcionParcial { get; set; }
        public DateTime AnioNota { get; set; }
        public bool EsActivoNota { get; set; }
    }
}
