// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class HoraDetailDto
    {
        public int? HorarioId { get; set; }
        public string Hora { get; set; }
        public string NombreUsuarioRegistraHorario { get; set; }
        public DateTime? FechaRegistroHorario { get; set; }
        public string NombreUsuarioModificaHorario { get; set; }
        public DateTime? FechaModificacionHorario { get; set; }
    }
}
