// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class SeccionDetailDto
    {
        public int? SeccionId { get; set; }
        public string DescripcionSeccion { get; set; }
        public string NombreUsuarioRegistraSeccion { get; set; }
        public DateTime? FechaRegistroSeccion { get; set; }
        public string NombreUsuarioModificaSeccion { get; set; }
        public DateTime? FechaModificacionSeccion { get; set; }
    }
}
