// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class MateriaFindDto
    {
        public int MateriaId { get; set; }
        public string NombreMateria { get; set; }
        public string DescripcionDuracion { get; set; }
        public bool EsActivoMateria { get; set; }
    }
}
