// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class SemestreDetailDto
    {
        public int? SemestreId { get; set; }
        public string DescripcionSemestre { get; set; }
        public string EsActivoSemestre { get; set; }
        public string NombreUsuarioRegistraSemestre { get; set; }
        public DateTime? FechaRegistroSemestre { get; set; }
        public string NombreUsuarioModificaSemestre { get; set; }
        public DateTime? FechaModificacionSemestre { get; set; }
    }
}
