// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class UsuarioListSeguridadDto
    {
        public int UsuarioId { get; set; }
        public string NombresPersona { get; set; }
        public string NombreUsuario { get; set; }
        public string DescripcionRol { get; set; }
    }
}
