// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class AulaDetailDto
    {
        public int? AulaId { get; set; }
        public string DescripcionAula { get; set; }
        public string NombreUsuarioRegistraAula { get; set; }
        public DateTime? FechaRegistroAula { get; set; }
        public string NombreUsuarioModificaAula { get; set; }
        public DateTime? FechaModificacionAula { get; set; }
    }
}
