// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Colegial.Entities.DTOs
{
    public partial class EventoErrorDto
    {
        public int? ErrorId { get; set; }
        public string NombreArchivoError { get; set; }
        public DateTime? FechaError { get; set; }
        public string RutaError { get; set; }
        public string MensajeError { get; set; }
        public string InnerExceptionError { get; set; }
    }
}